###########################################################################
# Auto generated cosimulation 'tclstart' script 
###########################################################################
#  Source Model         : DUALportRAMinterface_test
#  Generated Model      : gm_DUALportRAMinterface_test
#  Cosimulation Model   : gm_DUALportRAMinterface_test_vs
#
#  Source DUT           : gm_DUALportRAMinterface_test_vs/PL
#  Cosimulation DUT     : gm_DUALportRAMinterface_test_vs/PL_vs
#
#  File Location        : DUAL_port_BRAM_test\hdlsrc\DUALportRAMinterface_test\gm_DUALportRAMinterface_test_vs.tcl
#  Created              : 2024-05-14 09:54:20
#
#  Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
###########################################################################

###########################################################################
#  ClockName           : clk
#  ResetName           : reset_x 
#  ClockEnableName     : clk_enable
#
#  ClockLowTime        : 5ns
#  ClockHighTime       : 5ns
#  ClockPeriod         : 10ns
#
#  ResetLength         : 20ns
#  ClockEnableDelay    : 10ns
#  HoldTime            : 2ns
###########################################################################

###########################################################################
#  ModelBaseSampleTime   : 7.50008e-06
#  DutBaseSampleTime     : 7.50008e-06
#  OverClockFactor     : 1
###########################################################################

###########################################################################
#  Mapping of DutBaseSampleTime to ClockPeriod
#
#  N = (ClockPeriod / DutBaseSampleTime) * OverClockFactor
#  1 sec in Simulink corresponds to 1.33332e+06ns in the HDL Simulator(N = 1.33332e+06)
#
###########################################################################

###########################################################################
#  ResetHighAt          : (ClockLowTime + ResetLength + HoldTime)
#  ResetRiseEdge        : 27ns
#  ResetType            : sync
#  ResetAssertedLevel   : 0
#
#  ClockEnableHighAt    : (ClockLowTime + ResetLength + ClockEnableDelay + HoldTime)
#  ClockEnableRiseEdge  : 37ns
###########################################################################


exec xvlog index_counter.v Chart.v PL.v 
exec xelab PL --timescale 1ps/1ps --override_timeunit --override_timeprecision -dll --snapshot design -debug wave 

cd ../../../

# The xsim.dir must be in PWD
# - save off existing xsim.dir
if {[file exists xsim.dir] == 1} {
    set mtime [file mtime xsim.dir]
    set mtimestamp [clock format $mtime -format %Y%m%d_%H%M%S]
    set xsim_savefile "xsim.dir.$mtimestamp"
    file rename xsim.dir $xsim_savefile
}
# - copy up newly elaborated xsim.dir area from project to the current working directory.
set proj_xsim_dir {DUAL_port_BRAM_test\hdlsrc\DUALportRAMinterface_test/xsim.dir}
set proj_mtime [file mtime "$proj_xsim_dir/design"]
file copy -force $proj_xsim_dir .
file mtime xsim.dir $proj_mtime

