// -------------------------------------------------------------
// 
// File Name: DUAL_port_BRAM_test\hdlsrc\DUALportRAMinterface_test\index_counter.v
// Created: 2024-05-15 22:08:20
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: index_counter
// Source Path: DUALportRAMinterface_test/PL/index_counter
// Hierarchy Level: 1
// Model version: 1.58
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module index_counter
          (clk,
           reset_x,
           enb,
           In1,
           In2,
           index_counter_1);


  input   clk;
  input   reset_x;
  input   enb;
  input   In1;
  input   In2;
  output  [15:0] index_counter_1;  // uint16


  wire switch_compare_1;
  wire [15:0] Constant19_out1;  // uint16
  wire [15:0] Constant18_out1;  // uint16
  wire [15:0] Switch_out1;  // uint16
  wire switch_compare_1_1;
  wire [15:0] Constant20_out1;  // uint16
  reg [15:0] Delay_out1;  // uint16
  wire [15:0] Switch8_out1;  // uint16
  wire [15:0] Add_out1;  // uint16


  assign switch_compare_1 = In1 > 1'b0;



  assign Constant19_out1 = 16'b0000000000000000;



  assign Constant18_out1 = 16'b0000000000000001;



  assign Switch_out1 = (switch_compare_1 == 1'b0 ? Constant19_out1 :
              Constant18_out1);



  assign switch_compare_1_1 = In2 > 1'b0;



  assign Constant20_out1 = 16'b0000000000000000;



  assign Switch8_out1 = (switch_compare_1_1 == 1'b0 ? Delay_out1 :
              Constant20_out1);



  assign Add_out1 = Switch_out1 + Switch8_out1;



  always @(posedge clk)
    begin : Delay_process
      if (reset_x == 1'b0) begin
        Delay_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= Add_out1;
        end
      end
    end



  assign index_counter_1 = Delay_out1;

endmodule  // index_counter

