add_files -fileset sim_1 -norecurse C:/Users/Simon/Documents/Thesis_SDGA_3/matlab/DUAL_port_BRAM_test/hdlsrc/DUALportRAMinterface_test/index_counter.v
add_files -fileset sim_1 -norecurse C:/Users/Simon/Documents/Thesis_SDGA_3/matlab/DUAL_port_BRAM_test/hdlsrc/DUALportRAMinterface_test/Subsystem.v
add_files -fileset sim_1 -norecurse C:/Users/Simon/Documents/Thesis_SDGA_3/matlab/DUAL_port_BRAM_test/hdlsrc/DUALportRAMinterface_test/Subsystem1.v
add_files -fileset sim_1 -norecurse C:/Users/Simon/Documents/Thesis_SDGA_3/matlab/DUAL_port_BRAM_test/hdlsrc/DUALportRAMinterface_test/Subsystem2.v
add_files -fileset sim_1 -norecurse C:/Users/Simon/Documents/Thesis_SDGA_3/matlab/DUAL_port_BRAM_test/hdlsrc/DUALportRAMinterface_test/Subsystem3.v
add_files -fileset sim_1 -norecurse C:/Users/Simon/Documents/Thesis_SDGA_3/matlab/DUAL_port_BRAM_test/hdlsrc/DUALportRAMinterface_test/Subsystem4.v
add_files -fileset sim_1 -norecurse C:/Users/Simon/Documents/Thesis_SDGA_3/matlab/DUAL_port_BRAM_test/hdlsrc/DUALportRAMinterface_test/Subsystem5.v
add_files -fileset sim_1 -norecurse C:/Users/Simon/Documents/Thesis_SDGA_3/matlab/DUAL_port_BRAM_test/hdlsrc/DUALportRAMinterface_test/Subsystem6.v
add_files -fileset sim_1 -norecurse C:/Users/Simon/Documents/Thesis_SDGA_3/matlab/DUAL_port_BRAM_test/hdlsrc/DUALportRAMinterface_test/individual1.v
add_files -fileset sim_1 -norecurse C:/Users/Simon/Documents/Thesis_SDGA_3/matlab/DUAL_port_BRAM_test/hdlsrc/DUALportRAMinterface_test/Chart.v
add_files -fileset sim_1 -norecurse C:/Users/Simon/Documents/Thesis_SDGA_3/matlab/DUAL_port_BRAM_test/hdlsrc/DUALportRAMinterface_test/PL.v
