// -------------------------------------------------------------
// 
// File Name: DUAL_port_BRAM_test\hdlsrc\DUALportRAMinterface_test\Subsystem4.v
// Created: 2024-05-15 22:08:20
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem4
// Source Path: DUALportRAMinterface_test/PL/individual1/Subsystem4
// Hierarchy Level: 2
// Model version: 1.58
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem4
          (clk,
           reset_x,
           enb,
           reg_in,
           enable,
           reg_out);


  input   clk;
  input   reset_x;
  input   enb;
  input   [31:0] reg_in;  // uint32
  input   enable;
  output  [31:0] reg_out;  // uint32


  wire switch_compare_1;
  reg [31:0] Delay_out1;  // uint32
  wire [31:0] Switch_out1;  // uint32


  assign switch_compare_1 = enable > 1'b0;



  assign Switch_out1 = (switch_compare_1 == 1'b0 ? Delay_out1 :
              reg_in);



  always @(posedge clk)
    begin : Delay_process
      if (reset_x == 1'b0) begin
        Delay_out1 <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= Switch_out1;
        end
      end
    end



  assign reg_out = Delay_out1;

endmodule  // Subsystem4

