// -------------------------------------------------------------
// 
// File Name: DUAL_port_RAM_and_GA4\hdlsrc\DUALportRAMinterface_v3\alpha4_ss.v
// Created: 2024-05-15 10:45:59
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: alpha4_ss
// Source Path: DUALportRAMinterface_v3/PL/integration_block1/Subsystem/16bLFSR/4_ss
// Hierarchy Level: 4
// Model version: 1.52
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module alpha4_ss
          (clk,
           reset_x,
           enb,
           reg_in,
           reg_out);


  input   clk;
  input   reset_x;
  input   enb;
  input   reg_in;
  output  reg_out;


  reg  Delay_out1;


  always @(posedge clk)
    begin : Delay_process
      if (reset_x == 1'b0) begin
        Delay_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay_out1 <= reg_in;
        end
      end
    end



  assign reg_out = Delay_out1;

endmodule  // alpha4_ss

