// -------------------------------------------------------------
// 
// File Name: DUAL_port_RAM_and_GA4\hdlsrc\DUALportRAMinterface_v3\b4_random.v
// Created: 2024-05-15 10:45:59
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: b4_random
// Source Path: DUALportRAMinterface_v3/PL/integration_block1/Subsystem/b4_random
// Hierarchy Level: 3
// Model version: 1.52
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module b4_random
          (clk,
           reset_x,
           enb,
           In1,
           In2,
           Out1);


  input   clk;
  input   reset_x;
  input   enb;
  input   [15:0] In1;  // uint16
  input   In2;
  output  signed [17:0] Out1;  // sfix18_En15


  wire [31:0] Data_Type_Conversion12_out1;  // ufix32_En16
  wire [31:0] Bit_Shift4_out1;  // ufix32_En16
  wire [10:0] Data_Type_Conversion14_out1;  // ufix11_En11
  wire Constant_out1deadIn;
  wire [50:0] Modulo_by_Constant_HDL_Optimized_out1;  // ufix51_En62
  wire Modulo_by_Constant_HDL_Optimized_out2deadOut;
  wire signed [17:0] Data_Type_Conversion13_out1;  // sfix18_En16
  wire signed [17:0] Constant4_out1;  // sfix18_En15
  wire switch_compare_1;
  wire signed [19:0] Add9_add_cast;  // sfix20_En16
  wire signed [19:0] Add9_add_cast_1;  // sfix20_En16
  wire signed [19:0] Add9_add_temp;  // sfix20_En16
  wire signed [17:0] Add9_out1;  // sfix18_En16
  wire signed [17:0] Add9_out1_dtc;  // sfix18_En15
  wire signed [19:0] Add8_sub_cast;  // sfix20_En16
  wire signed [19:0] Add8_sub_cast_1;  // sfix20_En16
  wire signed [19:0] Add8_sub_temp;  // sfix20_En16
  wire signed [17:0] Add8_out1;  // sfix18_En15
  wire signed [17:0] Switch4_out1;  // sfix18_En15


  assign Data_Type_Conversion12_out1 = {In1, 16'b0000000000000000};



  assign Bit_Shift4_out1 = Data_Type_Conversion12_out1 >> 8'd28;



  assign Data_Type_Conversion14_out1 = Bit_Shift4_out1[15:5];



  assign Constant_out1deadIn = 1'b0;



  modimpl_ntwk_block4 u_mod_by_constant (.clk(clk),
                                         .reset_x(reset_x),
                                         .enb(enb),
                                         .X(Data_Type_Conversion14_out1),  // ufix11_En11
                                         .validIn(Constant_out1deadIn),
                                         .Y(Modulo_by_Constant_HDL_Optimized_out1),  // ufix51_En62
                                         .validOut(Modulo_by_Constant_HDL_Optimized_out2deadOut)
                                         );

  assign Data_Type_Conversion13_out1 = {13'b0, Modulo_by_Constant_HDL_Optimized_out1[50:46]};



  assign Constant4_out1 = 18'sb111111110011110001;



  assign switch_compare_1 = In2 > 1'b0;



  assign Add9_add_cast = {{2{Data_Type_Conversion13_out1[17]}}, Data_Type_Conversion13_out1};
  assign Add9_add_cast_1 = {Constant4_out1[17], {Constant4_out1, 1'b0}};
  assign Add9_add_temp = Add9_add_cast + Add9_add_cast_1;
  assign Add9_out1 = Add9_add_temp[17:0];



  assign Add9_out1_dtc = {Add9_out1[17], Add9_out1[17:1]};



  assign Add8_sub_cast = {Constant4_out1[17], {Constant4_out1, 1'b0}};
  assign Add8_sub_cast_1 = {{2{Data_Type_Conversion13_out1[17]}}, Data_Type_Conversion13_out1};
  assign Add8_sub_temp = Add8_sub_cast - Add8_sub_cast_1;
  assign Add8_out1 = Add8_sub_temp[18:1];



  assign Switch4_out1 = (switch_compare_1 == 1'b0 ? Add9_out1_dtc :
              Add8_out1);



  assign Out1 = Switch4_out1;

endmodule  // b4_random

