# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_example/zynq_example.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_example || ORIG_REF_NAME==zynq_example} -quiet] -quiet

# IP: bd/zynq_example/ip/zynq_example_processing_system7_0_0/zynq_example_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_example_processing_system7_0_0 || ORIG_REF_NAME==zynq_example_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_example/ip/zynq_example_proc_sys_reset_0_0/zynq_example_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_example_proc_sys_reset_0_0 || ORIG_REF_NAME==zynq_example_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zynq_example/ip/zynq_example_xbar_0/zynq_example_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_example_xbar_0 || ORIG_REF_NAME==zynq_example_xbar_0} -quiet] -quiet

# IP: bd/zynq_example/ip/zynq_example_auto_pc_1/zynq_example_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_example_auto_pc_1 || ORIG_REF_NAME==zynq_example_auto_pc_1} -quiet] -quiet

# IP: bd/zynq_example/ip/zynq_example_auto_pc_0/zynq_example_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_example_auto_pc_0 || ORIG_REF_NAME==zynq_example_auto_pc_0} -quiet] -quiet

# IP: bd/zynq_example/ip/zynq_example_axi_interconnect_0_0/zynq_example_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_example_axi_interconnect_0_0 || ORIG_REF_NAME==zynq_example_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/zynq_example/ip/zynq_example_axi_bram_ctrl_0_0/zynq_example_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_example_axi_bram_ctrl_0_0 || ORIG_REF_NAME==zynq_example_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/zynq_example/ip/zynq_example_blk_mem_gen_0_0/zynq_example_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_example_blk_mem_gen_0_0 || ORIG_REF_NAME==zynq_example_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/zynq_example/ip/zynq_example_axi_gpio_0_1/zynq_example_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_example_axi_gpio_0_1 || ORIG_REF_NAME==zynq_example_axi_gpio_0_1} -quiet] -quiet

# XDC: c:/Users/Simon/Documents/VIVADO_projects/project_2/project_2.gen/sources_1/bd/zynq_example/zynq_example_ooc.xdc
