// -------------------------------------------------------------
// 
// File Name: DUAL_port_RAM_and_GA4\hdlsrc\DUALportRAMinterface_v3\Chart1.v
// Created: 2024-05-15 10:45:59
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Chart1
// Source Path: DUALportRAMinterface_v3/PL/integration_block1/FIFO_system1/Chart1
// Hierarchy Level: 3
// Model version: 1.52
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Chart1
          (clk,
           reset_x,
           enb,
           counter,
           en_out,
           enable_counter);

  // Default encoded enumeration values for type state_type_is_Chart11
  parameter state_type_is_Chart11_IN_counter_state = 1'd0, state_type_is_Chart11_IN_initial_counter = 1'd1;

  input   clk;
  input   reset_x;
  input   enb;
  input   [12:0] counter;  // ufix13
  input   en_out;
  output  enable_counter;


  reg  is_Chart1;  // uint8
  reg  enable_counter_reg;
  reg  is_Chart1_next;  // enum type state_type_is_Chart11 (2 enums)
  reg  enable_counter_reg_next;


  always @(posedge clk)
    begin : Chart1_1_process
      if (reset_x == 1'b0) begin
        enable_counter_reg <= 1'b0;
        is_Chart1 <= state_type_is_Chart11_IN_initial_counter;
      end
      else begin
        if (enb) begin
          is_Chart1 <= is_Chart1_next;
          enable_counter_reg <= enable_counter_reg_next;
        end
      end
    end

  always @(counter, en_out, enable_counter_reg, is_Chart1) begin
    enable_counter_reg_next = enable_counter_reg;
    is_Chart1_next = is_Chart1;
    case ( is_Chart1)
      state_type_is_Chart11_IN_counter_state :
        begin
          if (counter == 13'b1100000000010) begin
            is_Chart1_next = state_type_is_Chart11_IN_initial_counter;
          end
          else begin
            enable_counter_reg_next = 1'b1;
          end
        end
      default :
        begin
          //case IN_initial_counter:
          if (en_out) begin
            is_Chart1_next = state_type_is_Chart11_IN_counter_state;
          end
          else begin
            enable_counter_reg_next = 1'b0;
          end
        end
    endcase
  end

  assign enable_counter = enable_counter_reg_next;



endmodule  // Chart1

