// -------------------------------------------------------------
// 
// File Name: DUAL_port_RAM_and_GA4\hdlsrc\DUALportRAMinterface_v3\Subsystem2_block7.v
// Created: 2024-05-15 10:45:59
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem2_block7
// Source Path: DUALportRAMinterface_v3/PL/integration_block1/D2/individual1/Subsystem2
// Hierarchy Level: 4
// Model version: 1.52
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem2_block7
          (clk,
           reset_x,
           enb,
           reg_in,
           enable,
           reg_out);


  input   clk;
  input   reset_x;
  input   enb;
  input   signed [32:0] reg_in;  // sfix33_En15
  input   enable;
  output  signed [32:0] reg_out;  // sfix33_En15


  wire switch_compare_1;
  reg signed [32:0] Delay_out1;  // sfix33_En15
  wire signed [32:0] Switch_out1;  // sfix33_En15


  assign switch_compare_1 = enable > 1'b0;



  assign Switch_out1 = (switch_compare_1 == 1'b0 ? Delay_out1 :
              reg_in);



  always @(posedge clk)
    begin : Delay_process
      if (reset_x == 1'b0) begin
        Delay_out1 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= Switch_out1;
        end
      end
    end



  assign reg_out = Delay_out1;

endmodule  // Subsystem2_block7

