// -------------------------------------------------------------
// 
// File Name: DUAL_port_RAM_and_GA4\hdlsrc\DUALportRAMinterface_v3\swap_counter1.v
// Created: 2024-05-15 10:45:59
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: swap_counter1
// Source Path: DUALportRAMinterface_v3/PL/integration_block1/GA_main/coefficent_array/swap_counter1
// Hierarchy Level: 4
// Model version: 1.52
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module swap_counter1
          (clk,
           reset_x,
           enb,
           In1,
           In2,
           Out1);


  input   clk;
  input   reset_x;
  input   enb;
  input   In1;
  input   In2;
  output  [3:0] Out1;  // ufix4


  wire switch_compare_1;
  wire [3:0] Constant19_out1;  // ufix4
  wire [3:0] Constant18_out1;  // ufix4
  wire [3:0] Switch_out1;  // ufix4
  wire switch_compare_1_1;
  wire [3:0] Constant20_out1;  // ufix4
  reg [3:0] Delay_out1;  // ufix4
  wire [3:0] Switch8_out1;  // ufix4
  wire [3:0] Add_out1;  // ufix4


  assign switch_compare_1 = In1 > 1'b0;



  assign Constant19_out1 = 4'b0000;



  assign Constant18_out1 = 4'b0001;



  assign Switch_out1 = (switch_compare_1 == 1'b0 ? Constant19_out1 :
              Constant18_out1);



  assign switch_compare_1_1 = In2 > 1'b0;



  assign Constant20_out1 = 4'b0001;



  assign Switch8_out1 = (switch_compare_1_1 == 1'b0 ? Delay_out1 :
              Constant20_out1);



  assign Add_out1 = Switch_out1 + Switch8_out1;



  always @(posedge clk)
    begin : Delay_process
      if (reset_x == 1'b0) begin
        Delay_out1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= Add_out1;
        end
      end
    end



  assign Out1 = Delay_out1;

endmodule  // swap_counter1

