// -------------------------------------------------------------
// 
// File Name: DUAL_port_RAM_and_GA4\hdlsrc\DUALportRAMinterface_v3\TWDLROM.v
// Created: 2024-05-15 10:45:59
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: TWDLROM
// Source Path: DUALportRAMinterface_v3/PL/integration_block1/FFT/TWDLROM
// Hierarchy Level: 3
// Model version: 1.52
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module TWDLROM
          (clk,
           reset_x,
           enb,
           dMemOutDly_vld,
           stage,
           initIC,
           syncReset,
           twdl_re,
           twdl_im,
           twdl_vld);


  input   clk;
  input   reset_x;
  input   enb;
  input   dMemOutDly_vld;
  input   [3:0] stage;  // ufix4
  input   initIC;
  input   syncReset;
  output  signed [27:0] twdl_re;  // sfix28_En26
  output  signed [27:0] twdl_im;  // sfix28_En26
  output  twdl_vld;


  reg [10:0] minResRX2FFTTwdlMapping_baseAddr;  // ufix11
  reg [10:0] minResRX2FFTTwdlMapping_cnt;  // ufix11
  reg [2:0] minResRX2FFTTwdlMapping_octantReg1;  // ufix3
  reg [11:0] minResRX2FFTTwdlMapping_twdlAddr_raw;  // ufix12
  reg [8:0] minResRX2FFTTwdlMapping_twdlAddrMap;  // ufix9
  reg  minResRX2FFTTwdlMapping_twdl45Reg;
  reg  minResRX2FFTTwdlMapping_dvldReg1;
  reg  minResRX2FFTTwdlMapping_dvldReg2;
  reg [10:0] minResRX2FFTTwdlMapping_maxCnt;  // ufix11
  reg [10:0] minResRX2FFTTwdlMapping_baseAddr_next;  // ufix11
  reg [10:0] minResRX2FFTTwdlMapping_cnt_next;  // ufix11
  reg [2:0] minResRX2FFTTwdlMapping_octantReg1_next;  // ufix3
  reg [11:0] minResRX2FFTTwdlMapping_twdlAddr_raw_next;  // ufix12
  reg [8:0] minResRX2FFTTwdlMapping_twdlAddrMap_next;  // ufix9
  reg  minResRX2FFTTwdlMapping_twdl45Reg_next;
  reg  minResRX2FFTTwdlMapping_dvldReg1_next;
  reg  minResRX2FFTTwdlMapping_dvldReg2_next;
  reg [10:0] minResRX2FFTTwdlMapping_maxCnt_next;  // ufix11
  reg [8:0] twdlAddr;  // ufix9
  reg  twdlAddrVld;
  reg [2:0] twdlOctant;  // ufix3
  reg  twdl45;
  wire signed [27:0] Twiddle_re_table_data [0:511];  // sfix28_En26 [512]
  wire signed [27:0] twiddleS_re;  // sfix28_En26
  reg signed [27:0] twiddleReg_re;  // sfix28_En26
  wire signed [27:0] Twiddle_im_table_data [0:511];  // sfix28_En26 [512]
  wire signed [27:0] twiddleS_im;  // sfix28_En26
  reg signed [27:0] twiddleReg_im;  // sfix28_En26
  reg [2:0] twdlOctantReg;  // ufix3
  reg  twdl45Reg;
  reg signed [27:0] twdl_re_1;  // sfix28_En26
  reg signed [27:0] twdl_im_1;  // sfix28_En26
  reg [2:0] minResRX2FFTTwdlMapping_octant;  // ufix3
  reg signed [25:0] minResRX2FFTTwdlMapping_sub_cast;  // sfix26_En9
  reg signed [25:0] minResRX2FFTTwdlMapping_sub_temp;  // sfix26_En9
  reg signed [13:0] minResRX2FFTTwdlMapping_sub_temp_0;  // sfix14
  reg signed [13:0] minResRX2FFTTwdlMapping_sub_temp_1;  // sfix14
  reg signed [25:0] minResRX2FFTTwdlMapping_sub_cast_0;  // sfix26_En9
  reg signed [25:0] minResRX2FFTTwdlMapping_sub_temp_2;  // sfix26_En9
  reg signed [25:0] minResRX2FFTTwdlMapping_sub_cast_1;  // sfix26_En9
  reg signed [25:0] minResRX2FFTTwdlMapping_sub_temp_3;  // sfix26_En9
  reg [10:0] minResRX2FFTTwdlMapping_t_0_0;  // ufix11
  reg signed [13:0] minResRX2FFTTwdlMapping_t_1;  // sfix14
  reg signed [13:0] minResRX2FFTTwdlMapping_t_2_0;  // sfix14
  reg signed [27:0] Radix22TwdlOctCorr_twdlIn_re;  // sfix28_En26
  reg signed [27:0] Radix22TwdlOctCorr_twdlIn_im;  // sfix28_En26
  reg signed [28:0] Radix22TwdlOctCorr_cast;  // sfix29_En26
  reg signed [28:0] Radix22TwdlOctCorr_cast_0;  // sfix29_En26
  reg signed [28:0] Radix22TwdlOctCorr_cast_1;  // sfix29_En26
  reg signed [28:0] Radix22TwdlOctCorr_cast_2;  // sfix29_En26
  reg signed [28:0] Radix22TwdlOctCorr_cast_3;  // sfix29_En26
  reg signed [28:0] Radix22TwdlOctCorr_cast_4;  // sfix29_En26
  reg signed [28:0] Radix22TwdlOctCorr_cast_5;  // sfix29_En26
  reg signed [28:0] Radix22TwdlOctCorr_cast_6;  // sfix29_En26
  reg signed [28:0] Radix22TwdlOctCorr_cast_7;  // sfix29_En26
  reg signed [28:0] Radix22TwdlOctCorr_cast_8;  // sfix29_En26
  reg signed [28:0] Radix22TwdlOctCorr_cast_9;  // sfix29_En26
  reg signed [28:0] Radix22TwdlOctCorr_cast_10;  // sfix29_En26


  // minResRX2FFTTwdlMapping
  always @(posedge clk)
    begin : minResRX2FFTTwdlMapping_process
      if (reset_x == 1'b0) begin
        minResRX2FFTTwdlMapping_octantReg1 <= 3'b000;
        minResRX2FFTTwdlMapping_twdlAddr_raw <= 12'b000000000000;
        minResRX2FFTTwdlMapping_twdlAddrMap <= 9'b000000000;
        minResRX2FFTTwdlMapping_twdl45Reg <= 1'b0;
        minResRX2FFTTwdlMapping_dvldReg1 <= 1'b0;
        minResRX2FFTTwdlMapping_dvldReg2 <= 1'b0;
        minResRX2FFTTwdlMapping_baseAddr <= 11'b00000000000;
        minResRX2FFTTwdlMapping_cnt <= 11'b11111111111;
        minResRX2FFTTwdlMapping_maxCnt <= 11'b00000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            minResRX2FFTTwdlMapping_octantReg1 <= 3'b000;
            minResRX2FFTTwdlMapping_twdlAddr_raw <= 12'b000000000000;
            minResRX2FFTTwdlMapping_twdlAddrMap <= 9'b000000000;
            minResRX2FFTTwdlMapping_twdl45Reg <= 1'b0;
            minResRX2FFTTwdlMapping_dvldReg1 <= 1'b0;
            minResRX2FFTTwdlMapping_dvldReg2 <= 1'b0;
            minResRX2FFTTwdlMapping_baseAddr <= 11'b00000000000;
            minResRX2FFTTwdlMapping_cnt <= 11'b11111111111;
            minResRX2FFTTwdlMapping_maxCnt <= 11'b00000000000;
          end
          else begin
            minResRX2FFTTwdlMapping_baseAddr <= minResRX2FFTTwdlMapping_baseAddr_next;
            minResRX2FFTTwdlMapping_cnt <= minResRX2FFTTwdlMapping_cnt_next;
            minResRX2FFTTwdlMapping_octantReg1 <= minResRX2FFTTwdlMapping_octantReg1_next;
            minResRX2FFTTwdlMapping_twdlAddr_raw <= minResRX2FFTTwdlMapping_twdlAddr_raw_next;
            minResRX2FFTTwdlMapping_twdlAddrMap <= minResRX2FFTTwdlMapping_twdlAddrMap_next;
            minResRX2FFTTwdlMapping_twdl45Reg <= minResRX2FFTTwdlMapping_twdl45Reg_next;
            minResRX2FFTTwdlMapping_dvldReg1 <= minResRX2FFTTwdlMapping_dvldReg1_next;
            minResRX2FFTTwdlMapping_dvldReg2 <= minResRX2FFTTwdlMapping_dvldReg2_next;
            minResRX2FFTTwdlMapping_maxCnt <= minResRX2FFTTwdlMapping_maxCnt_next;
          end
        end
      end
    end

  always @(dMemOutDly_vld, initIC, minResRX2FFTTwdlMapping_baseAddr,
       minResRX2FFTTwdlMapping_cnt, minResRX2FFTTwdlMapping_dvldReg1,
       minResRX2FFTTwdlMapping_dvldReg2, minResRX2FFTTwdlMapping_maxCnt,
       minResRX2FFTTwdlMapping_octantReg1, minResRX2FFTTwdlMapping_twdl45Reg,
       minResRX2FFTTwdlMapping_twdlAddrMap,
       minResRX2FFTTwdlMapping_twdlAddr_raw, stage) begin
    minResRX2FFTTwdlMapping_sub_temp = 26'sb00000000000000000000000000;
    minResRX2FFTTwdlMapping_sub_temp_0 = 14'sb00000000000000;
    minResRX2FFTTwdlMapping_sub_temp_1 = 14'sb00000000000000;
    minResRX2FFTTwdlMapping_sub_temp_2 = 26'sb00000000000000000000000000;
    minResRX2FFTTwdlMapping_sub_temp_3 = 26'sb00000000000000000000000000;
    minResRX2FFTTwdlMapping_sub_cast_1 = 26'sb00000000000000000000000000;
    minResRX2FFTTwdlMapping_sub_cast_0 = 26'sb00000000000000000000000000;
    minResRX2FFTTwdlMapping_t_2_0 = 14'sb00000000000000;
    minResRX2FFTTwdlMapping_t_1 = 14'sb00000000000000;
    minResRX2FFTTwdlMapping_sub_cast = 26'sb00000000000000000000000000;
    minResRX2FFTTwdlMapping_baseAddr_next = minResRX2FFTTwdlMapping_baseAddr;
    minResRX2FFTTwdlMapping_cnt_next = minResRX2FFTTwdlMapping_cnt;
    minResRX2FFTTwdlMapping_maxCnt_next = minResRX2FFTTwdlMapping_maxCnt;
    minResRX2FFTTwdlMapping_dvldReg2_next = minResRX2FFTTwdlMapping_dvldReg1;
    minResRX2FFTTwdlMapping_dvldReg1_next = dMemOutDly_vld;
    case ( minResRX2FFTTwdlMapping_twdlAddr_raw)
      12'b001000000000 :
        begin
          minResRX2FFTTwdlMapping_octant = 3'b000;
          minResRX2FFTTwdlMapping_twdl45Reg_next = 1'b1;
        end
      12'b010000000000 :
        begin
          minResRX2FFTTwdlMapping_octant = 3'b001;
          minResRX2FFTTwdlMapping_twdl45Reg_next = 1'b0;
        end
      12'b011000000000 :
        begin
          minResRX2FFTTwdlMapping_octant = 3'b010;
          minResRX2FFTTwdlMapping_twdl45Reg_next = 1'b1;
        end
      12'b100000000000 :
        begin
          minResRX2FFTTwdlMapping_octant = 3'b011;
          minResRX2FFTTwdlMapping_twdl45Reg_next = 1'b0;
        end
      12'b101000000000 :
        begin
          minResRX2FFTTwdlMapping_octant = 3'b100;
          minResRX2FFTTwdlMapping_twdl45Reg_next = 1'b1;
        end
      default :
        begin
          minResRX2FFTTwdlMapping_octant = minResRX2FFTTwdlMapping_twdlAddr_raw[11:9];
          minResRX2FFTTwdlMapping_twdl45Reg_next = 1'b0;
        end
    endcase
    minResRX2FFTTwdlMapping_octantReg1_next = minResRX2FFTTwdlMapping_octant;
    case ( minResRX2FFTTwdlMapping_octant)
      3'b000 :
        begin
          minResRX2FFTTwdlMapping_twdlAddrMap_next = minResRX2FFTTwdlMapping_twdlAddr_raw[8:0];
        end
      3'b001 :
        begin
          minResRX2FFTTwdlMapping_t_1 = {2'b0, minResRX2FFTTwdlMapping_twdlAddr_raw};
          minResRX2FFTTwdlMapping_sub_temp_0 = 14'sb00010000000000 - minResRX2FFTTwdlMapping_t_1;
          minResRX2FFTTwdlMapping_twdlAddrMap_next = minResRX2FFTTwdlMapping_sub_temp_0[8:0];
        end
      3'b010 :
        begin
          minResRX2FFTTwdlMapping_t_2_0 = {2'b0, minResRX2FFTTwdlMapping_twdlAddr_raw};
          minResRX2FFTTwdlMapping_sub_temp_1 = minResRX2FFTTwdlMapping_t_2_0 - 14'sb00010000000000;
          minResRX2FFTTwdlMapping_twdlAddrMap_next = minResRX2FFTTwdlMapping_sub_temp_1[8:0];
        end
      3'b011 :
        begin
          minResRX2FFTTwdlMapping_sub_cast_0 = {5'b0, {minResRX2FFTTwdlMapping_twdlAddr_raw, 9'b000000000}};
          minResRX2FFTTwdlMapping_sub_temp_2 = 26'sb00000100000000000000000000 - minResRX2FFTTwdlMapping_sub_cast_0;
          minResRX2FFTTwdlMapping_twdlAddrMap_next = minResRX2FFTTwdlMapping_sub_temp_2[17:9];
        end
      3'b100 :
        begin
          minResRX2FFTTwdlMapping_sub_cast_1 = {5'b0, {minResRX2FFTTwdlMapping_twdlAddr_raw, 9'b000000000}};
          minResRX2FFTTwdlMapping_sub_temp_3 = minResRX2FFTTwdlMapping_sub_cast_1 - 26'sb00000100000000000000000000;
          minResRX2FFTTwdlMapping_twdlAddrMap_next = minResRX2FFTTwdlMapping_sub_temp_3[17:9];
        end
      default :
        begin
          minResRX2FFTTwdlMapping_sub_cast = {5'b0, {minResRX2FFTTwdlMapping_twdlAddr_raw, 9'b000000000}};
          minResRX2FFTTwdlMapping_sub_temp = 26'sb00000110000000000000000000 - minResRX2FFTTwdlMapping_sub_cast;
          minResRX2FFTTwdlMapping_twdlAddrMap_next = minResRX2FFTTwdlMapping_sub_temp[17:9];
        end
    endcase
    minResRX2FFTTwdlMapping_t_0_0 = {minResRX2FFTTwdlMapping_baseAddr[0], minResRX2FFTTwdlMapping_baseAddr[1], minResRX2FFTTwdlMapping_baseAddr[2], minResRX2FFTTwdlMapping_baseAddr[3], minResRX2FFTTwdlMapping_baseAddr[4], minResRX2FFTTwdlMapping_baseAddr[5], minResRX2FFTTwdlMapping_baseAddr[6], minResRX2FFTTwdlMapping_baseAddr[7], minResRX2FFTTwdlMapping_baseAddr[8], minResRX2FFTTwdlMapping_baseAddr[9], minResRX2FFTTwdlMapping_baseAddr[10]};
    minResRX2FFTTwdlMapping_twdlAddr_raw_next = {1'b0, minResRX2FFTTwdlMapping_t_0_0};
    if ( ! initIC) begin
      if (dMemOutDly_vld && (minResRX2FFTTwdlMapping_cnt == 11'b00000000000)) begin
        minResRX2FFTTwdlMapping_baseAddr_next = minResRX2FFTTwdlMapping_baseAddr + 11'b00000000001;
      end
    end
    else begin
      minResRX2FFTTwdlMapping_baseAddr_next = 11'b00000000000;
    end
    if ( ! initIC) begin
      if (dMemOutDly_vld) begin
        if (minResRX2FFTTwdlMapping_cnt == 11'b00000000000) begin
          minResRX2FFTTwdlMapping_cnt_next = minResRX2FFTTwdlMapping_maxCnt;
        end
        else begin
          minResRX2FFTTwdlMapping_cnt_next = minResRX2FFTTwdlMapping_cnt - 11'b00000000001;
        end
      end
    end
    else if (stage == 4'b0000) begin
      minResRX2FFTTwdlMapping_maxCnt_next = 11'b11111111111;
      minResRX2FFTTwdlMapping_cnt_next = 11'b11111111111;
    end
    else begin
      minResRX2FFTTwdlMapping_cnt_next = minResRX2FFTTwdlMapping_maxCnt >> 8'd1;
      minResRX2FFTTwdlMapping_maxCnt_next = minResRX2FFTTwdlMapping_maxCnt >> 8'd1;
    end
    twdlAddr = minResRX2FFTTwdlMapping_twdlAddrMap;
    twdlAddrVld = minResRX2FFTTwdlMapping_dvldReg2;
    twdlOctant = minResRX2FFTTwdlMapping_octantReg1;
    twdl45 = minResRX2FFTTwdlMapping_twdl45Reg;
  end



  // Twiddle ROM1
  assign Twiddle_re_table_data[0] = 28'sb0100000000000000000000000000;
  assign Twiddle_re_table_data[1] = 28'sb0011111111111111111110110001;
  assign Twiddle_re_table_data[2] = 28'sb0011111111111111111011000100;
  assign Twiddle_re_table_data[3] = 28'sb0011111111111111110100111001;
  assign Twiddle_re_table_data[4] = 28'sb0011111111111111101100010001;
  assign Twiddle_re_table_data[5] = 28'sb0011111111111111100001001010;
  assign Twiddle_re_table_data[6] = 28'sb0011111111111111010011100110;
  assign Twiddle_re_table_data[7] = 28'sb0011111111111111000011100011;
  assign Twiddle_re_table_data[8] = 28'sb0011111111111110110001000011;
  assign Twiddle_re_table_data[9] = 28'sb0011111111111110011100000101;
  assign Twiddle_re_table_data[10] = 28'sb0011111111111110000100101000;
  assign Twiddle_re_table_data[11] = 28'sb0011111111111101101010101110;
  assign Twiddle_re_table_data[12] = 28'sb0011111111111101001110010111;
  assign Twiddle_re_table_data[13] = 28'sb0011111111111100101111100001;
  assign Twiddle_re_table_data[14] = 28'sb0011111111111100001110001101;
  assign Twiddle_re_table_data[15] = 28'sb0011111111111011101010011011;
  assign Twiddle_re_table_data[16] = 28'sb0011111111111011000100001100;
  assign Twiddle_re_table_data[17] = 28'sb0011111111111010011011011111;
  assign Twiddle_re_table_data[18] = 28'sb0011111111111001110000010100;
  assign Twiddle_re_table_data[19] = 28'sb0011111111111001000010101011;
  assign Twiddle_re_table_data[20] = 28'sb0011111111111000010010100100;
  assign Twiddle_re_table_data[21] = 28'sb0011111111110111011111111111;
  assign Twiddle_re_table_data[22] = 28'sb0011111111110110101010111101;
  assign Twiddle_re_table_data[23] = 28'sb0011111111110101110011011100;
  assign Twiddle_re_table_data[24] = 28'sb0011111111110100111001011110;
  assign Twiddle_re_table_data[25] = 28'sb0011111111110011111101000010;
  assign Twiddle_re_table_data[26] = 28'sb0011111111110010111110001000;
  assign Twiddle_re_table_data[27] = 28'sb0011111111110001111100110001;
  assign Twiddle_re_table_data[28] = 28'sb0011111111110000111000111011;
  assign Twiddle_re_table_data[29] = 28'sb0011111111101111110010101000;
  assign Twiddle_re_table_data[30] = 28'sb0011111111101110101001110111;
  assign Twiddle_re_table_data[31] = 28'sb0011111111101101011110101001;
  assign Twiddle_re_table_data[32] = 28'sb0011111111101100010000111100;
  assign Twiddle_re_table_data[33] = 28'sb0011111111101011000000110010;
  assign Twiddle_re_table_data[34] = 28'sb0011111111101001101110001011;
  assign Twiddle_re_table_data[35] = 28'sb0011111111101000011001000101;
  assign Twiddle_re_table_data[36] = 28'sb0011111111100111000001100010;
  assign Twiddle_re_table_data[37] = 28'sb0011111111100101100111100001;
  assign Twiddle_re_table_data[38] = 28'sb0011111111100100001011000011;
  assign Twiddle_re_table_data[39] = 28'sb0011111111100010101100000110;
  assign Twiddle_re_table_data[40] = 28'sb0011111111100001001010101101;
  assign Twiddle_re_table_data[41] = 28'sb0011111111011111100110110101;
  assign Twiddle_re_table_data[42] = 28'sb0011111111011110000000100000;
  assign Twiddle_re_table_data[43] = 28'sb0011111111011100010111101110;
  assign Twiddle_re_table_data[44] = 28'sb0011111111011010101100011110;
  assign Twiddle_re_table_data[45] = 28'sb0011111111011000111110110000;
  assign Twiddle_re_table_data[46] = 28'sb0011111111010111001110100101;
  assign Twiddle_re_table_data[47] = 28'sb0011111111010101011011111100;
  assign Twiddle_re_table_data[48] = 28'sb0011111111010011100110110110;
  assign Twiddle_re_table_data[49] = 28'sb0011111111010001101111010010;
  assign Twiddle_re_table_data[50] = 28'sb0011111111001111110101010001;
  assign Twiddle_re_table_data[51] = 28'sb0011111111001101111000110010;
  assign Twiddle_re_table_data[52] = 28'sb0011111111001011111001110110;
  assign Twiddle_re_table_data[53] = 28'sb0011111111001001111000011100;
  assign Twiddle_re_table_data[54] = 28'sb0011111111000111110100100101;
  assign Twiddle_re_table_data[55] = 28'sb0011111111000101101110010001;
  assign Twiddle_re_table_data[56] = 28'sb0011111111000011100101100000;
  assign Twiddle_re_table_data[57] = 28'sb0011111111000001011010010001;
  assign Twiddle_re_table_data[58] = 28'sb0011111110111111001100100100;
  assign Twiddle_re_table_data[59] = 28'sb0011111110111100111100011011;
  assign Twiddle_re_table_data[60] = 28'sb0011111110111010101001110100;
  assign Twiddle_re_table_data[61] = 28'sb0011111110111000010100110000;
  assign Twiddle_re_table_data[62] = 28'sb0011111110110101111101001111;
  assign Twiddle_re_table_data[63] = 28'sb0011111110110011100011010000;
  assign Twiddle_re_table_data[64] = 28'sb0011111110110001000110110100;
  assign Twiddle_re_table_data[65] = 28'sb0011111110101110100111111100;
  assign Twiddle_re_table_data[66] = 28'sb0011111110101100000110100110;
  assign Twiddle_re_table_data[67] = 28'sb0011111110101001100010110011;
  assign Twiddle_re_table_data[68] = 28'sb0011111110100110111100100011;
  assign Twiddle_re_table_data[69] = 28'sb0011111110100100010011110101;
  assign Twiddle_re_table_data[70] = 28'sb0011111110100001101000101011;
  assign Twiddle_re_table_data[71] = 28'sb0011111110011110111011000100;
  assign Twiddle_re_table_data[72] = 28'sb0011111110011100001011000000;
  assign Twiddle_re_table_data[73] = 28'sb0011111110011001011000011111;
  assign Twiddle_re_table_data[74] = 28'sb0011111110010110100011100000;
  assign Twiddle_re_table_data[75] = 28'sb0011111110010011101100000101;
  assign Twiddle_re_table_data[76] = 28'sb0011111110010000110010001110;
  assign Twiddle_re_table_data[77] = 28'sb0011111110001101110101111001;
  assign Twiddle_re_table_data[78] = 28'sb0011111110001010110111000111;
  assign Twiddle_re_table_data[79] = 28'sb0011111110000111110101111001;
  assign Twiddle_re_table_data[80] = 28'sb0011111110000100110010001110;
  assign Twiddle_re_table_data[81] = 28'sb0011111110000001101100000110;
  assign Twiddle_re_table_data[82] = 28'sb0011111101111110100011100010;
  assign Twiddle_re_table_data[83] = 28'sb0011111101111011011000100001;
  assign Twiddle_re_table_data[84] = 28'sb0011111101111000001011000011;
  assign Twiddle_re_table_data[85] = 28'sb0011111101110100111011001001;
  assign Twiddle_re_table_data[86] = 28'sb0011111101110001101000110010;
  assign Twiddle_re_table_data[87] = 28'sb0011111101101110010011111110;
  assign Twiddle_re_table_data[88] = 28'sb0011111101101010111100101110;
  assign Twiddle_re_table_data[89] = 28'sb0011111101100111100011000010;
  assign Twiddle_re_table_data[90] = 28'sb0011111101100100000110111001;
  assign Twiddle_re_table_data[91] = 28'sb0011111101100000101000010011;
  assign Twiddle_re_table_data[92] = 28'sb0011111101011101000111010010;
  assign Twiddle_re_table_data[93] = 28'sb0011111101011001100011110100;
  assign Twiddle_re_table_data[94] = 28'sb0011111101010101111101111001;
  assign Twiddle_re_table_data[95] = 28'sb0011111101010010010101100011;
  assign Twiddle_re_table_data[96] = 28'sb0011111101001110101010110000;
  assign Twiddle_re_table_data[97] = 28'sb0011111101001010111101100001;
  assign Twiddle_re_table_data[98] = 28'sb0011111101000111001101110110;
  assign Twiddle_re_table_data[99] = 28'sb0011111101000011011011101110;
  assign Twiddle_re_table_data[100] = 28'sb0011111100111111100111001011;
  assign Twiddle_re_table_data[101] = 28'sb0011111100111011110000001011;
  assign Twiddle_re_table_data[102] = 28'sb0011111100110111110110110000;
  assign Twiddle_re_table_data[103] = 28'sb0011111100110011111010111000;
  assign Twiddle_re_table_data[104] = 28'sb0011111100101111111100100101;
  assign Twiddle_re_table_data[105] = 28'sb0011111100101011111011110101;
  assign Twiddle_re_table_data[106] = 28'sb0011111100100111111000101010;
  assign Twiddle_re_table_data[107] = 28'sb0011111100100011110011000011;
  assign Twiddle_re_table_data[108] = 28'sb0011111100011111101011000000;
  assign Twiddle_re_table_data[109] = 28'sb0011111100011011100000100001;
  assign Twiddle_re_table_data[110] = 28'sb0011111100010111010011100111;
  assign Twiddle_re_table_data[111] = 28'sb0011111100010011000100010001;
  assign Twiddle_re_table_data[112] = 28'sb0011111100001110110010011111;
  assign Twiddle_re_table_data[113] = 28'sb0011111100001010011110010010;
  assign Twiddle_re_table_data[114] = 28'sb0011111100000110000111101001;
  assign Twiddle_re_table_data[115] = 28'sb0011111100000001101110100101;
  assign Twiddle_re_table_data[116] = 28'sb0011111011111101010011000101;
  assign Twiddle_re_table_data[117] = 28'sb0011111011111000110101001010;
  assign Twiddle_re_table_data[118] = 28'sb0011111011110100010100110100;
  assign Twiddle_re_table_data[119] = 28'sb0011111011101111110010000010;
  assign Twiddle_re_table_data[120] = 28'sb0011111011101011001100110100;
  assign Twiddle_re_table_data[121] = 28'sb0011111011100110100101001100;
  assign Twiddle_re_table_data[122] = 28'sb0011111011100001111011001000;
  assign Twiddle_re_table_data[123] = 28'sb0011111011011101001110101010;
  assign Twiddle_re_table_data[124] = 28'sb0011111011011000011111110000;
  assign Twiddle_re_table_data[125] = 28'sb0011111011010011101110011011;
  assign Twiddle_re_table_data[126] = 28'sb0011111011001110111010101011;
  assign Twiddle_re_table_data[127] = 28'sb0011111011001010000100100000;
  assign Twiddle_re_table_data[128] = 28'sb0011111011000101001011111010;
  assign Twiddle_re_table_data[129] = 28'sb0011111011000000010000111001;
  assign Twiddle_re_table_data[130] = 28'sb0011111010111011010011011110;
  assign Twiddle_re_table_data[131] = 28'sb0011111010110110010011100111;
  assign Twiddle_re_table_data[132] = 28'sb0011111010110001010001010110;
  assign Twiddle_re_table_data[133] = 28'sb0011111010101100001100101010;
  assign Twiddle_re_table_data[134] = 28'sb0011111010100111000101100100;
  assign Twiddle_re_table_data[135] = 28'sb0011111010100001111100000011;
  assign Twiddle_re_table_data[136] = 28'sb0011111010011100110000000111;
  assign Twiddle_re_table_data[137] = 28'sb0011111010010111100001110001;
  assign Twiddle_re_table_data[138] = 28'sb0011111010010010010001000001;
  assign Twiddle_re_table_data[139] = 28'sb0011111010001100111101110110;
  assign Twiddle_re_table_data[140] = 28'sb0011111010000111101000010001;
  assign Twiddle_re_table_data[141] = 28'sb0011111010000010010000010001;
  assign Twiddle_re_table_data[142] = 28'sb0011111001111100110101111000;
  assign Twiddle_re_table_data[143] = 28'sb0011111001110111011001000100;
  assign Twiddle_re_table_data[144] = 28'sb0011111001110001111001110110;
  assign Twiddle_re_table_data[145] = 28'sb0011111001101100011000001101;
  assign Twiddle_re_table_data[146] = 28'sb0011111001100110110100001011;
  assign Twiddle_re_table_data[147] = 28'sb0011111001100001001101101111;
  assign Twiddle_re_table_data[148] = 28'sb0011111001011011100100111001;
  assign Twiddle_re_table_data[149] = 28'sb0011111001010101111001101001;
  assign Twiddle_re_table_data[150] = 28'sb0011111001010000001100000000;
  assign Twiddle_re_table_data[151] = 28'sb0011111001001010011011111100;
  assign Twiddle_re_table_data[152] = 28'sb0011111001000100101001011111;
  assign Twiddle_re_table_data[153] = 28'sb0011111000111110110100101000;
  assign Twiddle_re_table_data[154] = 28'sb0011111000111000111101011000;
  assign Twiddle_re_table_data[155] = 28'sb0011111000110011000011101110;
  assign Twiddle_re_table_data[156] = 28'sb0011111000101101000111101010;
  assign Twiddle_re_table_data[157] = 28'sb0011111000100111001001001110;
  assign Twiddle_re_table_data[158] = 28'sb0011111000100001001000011000;
  assign Twiddle_re_table_data[159] = 28'sb0011111000011011000101001000;
  assign Twiddle_re_table_data[160] = 28'sb0011111000010100111111011111;
  assign Twiddle_re_table_data[161] = 28'sb0011111000001110110111011110;
  assign Twiddle_re_table_data[162] = 28'sb0011111000001000101101000011;
  assign Twiddle_re_table_data[163] = 28'sb0011111000000010100000001111;
  assign Twiddle_re_table_data[164] = 28'sb0011110111111100010001000010;
  assign Twiddle_re_table_data[165] = 28'sb0011110111110101111111011100;
  assign Twiddle_re_table_data[166] = 28'sb0011110111101111101011011101;
  assign Twiddle_re_table_data[167] = 28'sb0011110111101001010101000101;
  assign Twiddle_re_table_data[168] = 28'sb0011110111100010111100010100;
  assign Twiddle_re_table_data[169] = 28'sb0011110111011100100001001011;
  assign Twiddle_re_table_data[170] = 28'sb0011110111010110000011101010;
  assign Twiddle_re_table_data[171] = 28'sb0011110111001111100011101111;
  assign Twiddle_re_table_data[172] = 28'sb0011110111001001000001011100;
  assign Twiddle_re_table_data[173] = 28'sb0011110111000010011100110001;
  assign Twiddle_re_table_data[174] = 28'sb0011110110111011110101101101;
  assign Twiddle_re_table_data[175] = 28'sb0011110110110101001100010001;
  assign Twiddle_re_table_data[176] = 28'sb0011110110101110100000011101;
  assign Twiddle_re_table_data[177] = 28'sb0011110110100111110010010000;
  assign Twiddle_re_table_data[178] = 28'sb0011110110100001000001101100;
  assign Twiddle_re_table_data[179] = 28'sb0011110110011010001110101111;
  assign Twiddle_re_table_data[180] = 28'sb0011110110010011011001011010;
  assign Twiddle_re_table_data[181] = 28'sb0011110110001100100001101110;
  assign Twiddle_re_table_data[182] = 28'sb0011110110000101100111101001;
  assign Twiddle_re_table_data[183] = 28'sb0011110101111110101011001101;
  assign Twiddle_re_table_data[184] = 28'sb0011110101110111101100011001;
  assign Twiddle_re_table_data[185] = 28'sb0011110101110000101011001101;
  assign Twiddle_re_table_data[186] = 28'sb0011110101101001100111101010;
  assign Twiddle_re_table_data[187] = 28'sb0011110101100010100001101111;
  assign Twiddle_re_table_data[188] = 28'sb0011110101011011011001011101;
  assign Twiddle_re_table_data[189] = 28'sb0011110101010100001110110011;
  assign Twiddle_re_table_data[190] = 28'sb0011110101001101000001110010;
  assign Twiddle_re_table_data[191] = 28'sb0011110101000101110010011010;
  assign Twiddle_re_table_data[192] = 28'sb0011110100111110100000101011;
  assign Twiddle_re_table_data[193] = 28'sb0011110100110111001100100100;
  assign Twiddle_re_table_data[194] = 28'sb0011110100101111110110000111;
  assign Twiddle_re_table_data[195] = 28'sb0011110100101000011101010010;
  assign Twiddle_re_table_data[196] = 28'sb0011110100100001000010000111;
  assign Twiddle_re_table_data[197] = 28'sb0011110100011001100100100100;
  assign Twiddle_re_table_data[198] = 28'sb0011110100010010000100101011;
  assign Twiddle_re_table_data[199] = 28'sb0011110100001010100010011100;
  assign Twiddle_re_table_data[200] = 28'sb0011110100000010111101110101;
  assign Twiddle_re_table_data[201] = 28'sb0011110011111011010110111001;
  assign Twiddle_re_table_data[202] = 28'sb0011110011110011101101100101;
  assign Twiddle_re_table_data[203] = 28'sb0011110011101100000001111011;
  assign Twiddle_re_table_data[204] = 28'sb0011110011100100010011111011;
  assign Twiddle_re_table_data[205] = 28'sb0011110011011100100011100101;
  assign Twiddle_re_table_data[206] = 28'sb0011110011010100110000111001;
  assign Twiddle_re_table_data[207] = 28'sb0011110011001100111011110110;
  assign Twiddle_re_table_data[208] = 28'sb0011110011000101000100011110;
  assign Twiddle_re_table_data[209] = 28'sb0011110010111101001010101111;
  assign Twiddle_re_table_data[210] = 28'sb0011110010110101001110101011;
  assign Twiddle_re_table_data[211] = 28'sb0011110010101101010000010000;
  assign Twiddle_re_table_data[212] = 28'sb0011110010100101001111100001;
  assign Twiddle_re_table_data[213] = 28'sb0011110010011101001100011011;
  assign Twiddle_re_table_data[214] = 28'sb0011110010010101000111000000;
  assign Twiddle_re_table_data[215] = 28'sb0011110010001100111111001111;
  assign Twiddle_re_table_data[216] = 28'sb0011110010000100110101001001;
  assign Twiddle_re_table_data[217] = 28'sb0011110001111100101000101110;
  assign Twiddle_re_table_data[218] = 28'sb0011110001110100011001111110;
  assign Twiddle_re_table_data[219] = 28'sb0011110001101100001000111000;
  assign Twiddle_re_table_data[220] = 28'sb0011110001100011110101011101;
  assign Twiddle_re_table_data[221] = 28'sb0011110001011011011111101101;
  assign Twiddle_re_table_data[222] = 28'sb0011110001010011000111101001;
  assign Twiddle_re_table_data[223] = 28'sb0011110001001010101101001111;
  assign Twiddle_re_table_data[224] = 28'sb0011110001000010010000100001;
  assign Twiddle_re_table_data[225] = 28'sb0011110000111001110001011110;
  assign Twiddle_re_table_data[226] = 28'sb0011110000110001010000000110;
  assign Twiddle_re_table_data[227] = 28'sb0011110000101000101100011010;
  assign Twiddle_re_table_data[228] = 28'sb0011110000100000000110011001;
  assign Twiddle_re_table_data[229] = 28'sb0011110000010111011110000100;
  assign Twiddle_re_table_data[230] = 28'sb0011110000001110110011011011;
  assign Twiddle_re_table_data[231] = 28'sb0011110000000110000110011110;
  assign Twiddle_re_table_data[232] = 28'sb0011101111111101010111001100;
  assign Twiddle_re_table_data[233] = 28'sb0011101111110100100101100111;
  assign Twiddle_re_table_data[234] = 28'sb0011101111101011110001101101;
  assign Twiddle_re_table_data[235] = 28'sb0011101111100010111011100000;
  assign Twiddle_re_table_data[236] = 28'sb0011101111011010000010111111;
  assign Twiddle_re_table_data[237] = 28'sb0011101111010001001000001010;
  assign Twiddle_re_table_data[238] = 28'sb0011101111001000001011000010;
  assign Twiddle_re_table_data[239] = 28'sb0011101110111111001011100110;
  assign Twiddle_re_table_data[240] = 28'sb0011101110110110001001110111;
  assign Twiddle_re_table_data[241] = 28'sb0011101110101101000101110100;
  assign Twiddle_re_table_data[242] = 28'sb0011101110100011111111011110;
  assign Twiddle_re_table_data[243] = 28'sb0011101110011010110110110101;
  assign Twiddle_re_table_data[244] = 28'sb0011101110010001101011111001;
  assign Twiddle_re_table_data[245] = 28'sb0011101110001000011110101010;
  assign Twiddle_re_table_data[246] = 28'sb0011101101111111001111001000;
  assign Twiddle_re_table_data[247] = 28'sb0011101101110101111101010100;
  assign Twiddle_re_table_data[248] = 28'sb0011101101101100101001001100;
  assign Twiddle_re_table_data[249] = 28'sb0011101101100011010010110010;
  assign Twiddle_re_table_data[250] = 28'sb0011101101011001111010000110;
  assign Twiddle_re_table_data[251] = 28'sb0011101101010000011111000111;
  assign Twiddle_re_table_data[252] = 28'sb0011101101000111000001110101;
  assign Twiddle_re_table_data[253] = 28'sb0011101100111101100010010010;
  assign Twiddle_re_table_data[254] = 28'sb0011101100110100000000011100;
  assign Twiddle_re_table_data[255] = 28'sb0011101100101010011100010100;
  assign Twiddle_re_table_data[256] = 28'sb0011101100100000110101111010;
  assign Twiddle_re_table_data[257] = 28'sb0011101100010111001101001110;
  assign Twiddle_re_table_data[258] = 28'sb0011101100001101100010010001;
  assign Twiddle_re_table_data[259] = 28'sb0011101100000011110101000001;
  assign Twiddle_re_table_data[260] = 28'sb0011101011111010000101100000;
  assign Twiddle_re_table_data[261] = 28'sb0011101011110000010011101110;
  assign Twiddle_re_table_data[262] = 28'sb0011101011100110011111101010;
  assign Twiddle_re_table_data[263] = 28'sb0011101011011100101001010101;
  assign Twiddle_re_table_data[264] = 28'sb0011101011010010110000101110;
  assign Twiddle_re_table_data[265] = 28'sb0011101011001000110101110111;
  assign Twiddle_re_table_data[266] = 28'sb0011101010111110111000101110;
  assign Twiddle_re_table_data[267] = 28'sb0011101010110100111001010101;
  assign Twiddle_re_table_data[268] = 28'sb0011101010101010110111101010;
  assign Twiddle_re_table_data[269] = 28'sb0011101010100000110011101111;
  assign Twiddle_re_table_data[270] = 28'sb0011101010010110101101100011;
  assign Twiddle_re_table_data[271] = 28'sb0011101010001100100101000111;
  assign Twiddle_re_table_data[272] = 28'sb0011101010000010011010011010;
  assign Twiddle_re_table_data[273] = 28'sb0011101001111000001101011101;
  assign Twiddle_re_table_data[274] = 28'sb0011101001101101111110001111;
  assign Twiddle_re_table_data[275] = 28'sb0011101001100011101100110010;
  assign Twiddle_re_table_data[276] = 28'sb0011101001011001011001000100;
  assign Twiddle_re_table_data[277] = 28'sb0011101001001111000011000110;
  assign Twiddle_re_table_data[278] = 28'sb0011101001000100101010111001;
  assign Twiddle_re_table_data[279] = 28'sb0011101000111010010000011100;
  assign Twiddle_re_table_data[280] = 28'sb0011101000101111110011101111;
  assign Twiddle_re_table_data[281] = 28'sb0011101000100101010100110010;
  assign Twiddle_re_table_data[282] = 28'sb0011101000011010110011100110;
  assign Twiddle_re_table_data[283] = 28'sb0011101000010000010000001011;
  assign Twiddle_re_table_data[284] = 28'sb0011101000000101101010100000;
  assign Twiddle_re_table_data[285] = 28'sb0011100111111011000010100110;
  assign Twiddle_re_table_data[286] = 28'sb0011100111110000011000011101;
  assign Twiddle_re_table_data[287] = 28'sb0011100111100101101100000101;
  assign Twiddle_re_table_data[288] = 28'sb0011100111011010111101011111;
  assign Twiddle_re_table_data[289] = 28'sb0011100111010000001100101001;
  assign Twiddle_re_table_data[290] = 28'sb0011100111000101011001100101;
  assign Twiddle_re_table_data[291] = 28'sb0011100110111010100100010010;
  assign Twiddle_re_table_data[292] = 28'sb0011100110101111101100110001;
  assign Twiddle_re_table_data[293] = 28'sb0011100110100100110011000010;
  assign Twiddle_re_table_data[294] = 28'sb0011100110011001110111000100;
  assign Twiddle_re_table_data[295] = 28'sb0011100110001110111000111000;
  assign Twiddle_re_table_data[296] = 28'sb0011100110000011111000011110;
  assign Twiddle_re_table_data[297] = 28'sb0011100101111000110101110111;
  assign Twiddle_re_table_data[298] = 28'sb0011100101101101110001000001;
  assign Twiddle_re_table_data[299] = 28'sb0011100101100010101001111110;
  assign Twiddle_re_table_data[300] = 28'sb0011100101010111100000101101;
  assign Twiddle_re_table_data[301] = 28'sb0011100101001100010101001111;
  assign Twiddle_re_table_data[302] = 28'sb0011100101000001000111100011;
  assign Twiddle_re_table_data[303] = 28'sb0011100100110101110111101010;
  assign Twiddle_re_table_data[304] = 28'sb0011100100101010100101100100;
  assign Twiddle_re_table_data[305] = 28'sb0011100100011111010001010001;
  assign Twiddle_re_table_data[306] = 28'sb0011100100010011111010110001;
  assign Twiddle_re_table_data[307] = 28'sb0011100100001000100010000100;
  assign Twiddle_re_table_data[308] = 28'sb0011100011111101000111001010;
  assign Twiddle_re_table_data[309] = 28'sb0011100011110001101010000100;
  assign Twiddle_re_table_data[310] = 28'sb0011100011100110001010110001;
  assign Twiddle_re_table_data[311] = 28'sb0011100011011010101001010010;
  assign Twiddle_re_table_data[312] = 28'sb0011100011001111000101100111;
  assign Twiddle_re_table_data[313] = 28'sb0011100011000011011111101111;
  assign Twiddle_re_table_data[314] = 28'sb0011100010110111110111101011;
  assign Twiddle_re_table_data[315] = 28'sb0011100010101100001101011100;
  assign Twiddle_re_table_data[316] = 28'sb0011100010100000100001000000;
  assign Twiddle_re_table_data[317] = 28'sb0011100010010100110010011001;
  assign Twiddle_re_table_data[318] = 28'sb0011100010001001000001100110;
  assign Twiddle_re_table_data[319] = 28'sb0011100001111101001110101000;
  assign Twiddle_re_table_data[320] = 28'sb0011100001110001011001011110;
  assign Twiddle_re_table_data[321] = 28'sb0011100001100101100010001001;
  assign Twiddle_re_table_data[322] = 28'sb0011100001011001101000101001;
  assign Twiddle_re_table_data[323] = 28'sb0011100001001101101100111110;
  assign Twiddle_re_table_data[324] = 28'sb0011100001000001101111001000;
  assign Twiddle_re_table_data[325] = 28'sb0011100000110101101111000111;
  assign Twiddle_re_table_data[326] = 28'sb0011100000101001101100111100;
  assign Twiddle_re_table_data[327] = 28'sb0011100000011101101000100101;
  assign Twiddle_re_table_data[328] = 28'sb0011100000010001100010000101;
  assign Twiddle_re_table_data[329] = 28'sb0011100000000101011001011010;
  assign Twiddle_re_table_data[330] = 28'sb0011011111111001001110100101;
  assign Twiddle_re_table_data[331] = 28'sb0011011111101101000001100101;
  assign Twiddle_re_table_data[332] = 28'sb0011011111100000110010011100;
  assign Twiddle_re_table_data[333] = 28'sb0011011111010100100001001001;
  assign Twiddle_re_table_data[334] = 28'sb0011011111001000001101101100;
  assign Twiddle_re_table_data[335] = 28'sb0011011110111011111000000110;
  assign Twiddle_re_table_data[336] = 28'sb0011011110101111100000010110;
  assign Twiddle_re_table_data[337] = 28'sb0011011110100011000110011100;
  assign Twiddle_re_table_data[338] = 28'sb0011011110010110101010011001;
  assign Twiddle_re_table_data[339] = 28'sb0011011110001010001100001101;
  assign Twiddle_re_table_data[340] = 28'sb0011011101111101101011111001;
  assign Twiddle_re_table_data[341] = 28'sb0011011101110001001001011011;
  assign Twiddle_re_table_data[342] = 28'sb0011011101100100100100110100;
  assign Twiddle_re_table_data[343] = 28'sb0011011101010111111110000101;
  assign Twiddle_re_table_data[344] = 28'sb0011011101001011010101001101;
  assign Twiddle_re_table_data[345] = 28'sb0011011100111110101010001101;
  assign Twiddle_re_table_data[346] = 28'sb0011011100110001111101000100;
  assign Twiddle_re_table_data[347] = 28'sb0011011100100101001101110011;
  assign Twiddle_re_table_data[348] = 28'sb0011011100011000011100011010;
  assign Twiddle_re_table_data[349] = 28'sb0011011100001011101000111001;
  assign Twiddle_re_table_data[350] = 28'sb0011011011111110110011010001;
  assign Twiddle_re_table_data[351] = 28'sb0011011011110001111011100001;
  assign Twiddle_re_table_data[352] = 28'sb0011011011100101000001101001;
  assign Twiddle_re_table_data[353] = 28'sb0011011011011000000101101001;
  assign Twiddle_re_table_data[354] = 28'sb0011011011001011000111100011;
  assign Twiddle_re_table_data[355] = 28'sb0011011010111110000111010101;
  assign Twiddle_re_table_data[356] = 28'sb0011011010110001000101000000;
  assign Twiddle_re_table_data[357] = 28'sb0011011010100100000000100100;
  assign Twiddle_re_table_data[358] = 28'sb0011011010010110111010000001;
  assign Twiddle_re_table_data[359] = 28'sb0011011010001001110001011000;
  assign Twiddle_re_table_data[360] = 28'sb0011011001111100100110101000;
  assign Twiddle_re_table_data[361] = 28'sb0011011001101111011001110001;
  assign Twiddle_re_table_data[362] = 28'sb0011011001100010001010110101;
  assign Twiddle_re_table_data[363] = 28'sb0011011001010100111001110010;
  assign Twiddle_re_table_data[364] = 28'sb0011011001000111100110101001;
  assign Twiddle_re_table_data[365] = 28'sb0011011000111010010001011010;
  assign Twiddle_re_table_data[366] = 28'sb0011011000101100111010000101;
  assign Twiddle_re_table_data[367] = 28'sb0011011000011111100000101011;
  assign Twiddle_re_table_data[368] = 28'sb0011011000010010000101001011;
  assign Twiddle_re_table_data[369] = 28'sb0011011000000100100111100110;
  assign Twiddle_re_table_data[370] = 28'sb0011010111110111000111111011;
  assign Twiddle_re_table_data[371] = 28'sb0011010111101001100110001011;
  assign Twiddle_re_table_data[372] = 28'sb0011010111011100000010010111;
  assign Twiddle_re_table_data[373] = 28'sb0011010111001110011100011101;
  assign Twiddle_re_table_data[374] = 28'sb0011010111000000110100011110;
  assign Twiddle_re_table_data[375] = 28'sb0011010110110011001010011011;
  assign Twiddle_re_table_data[376] = 28'sb0011010110100101011110010100;
  assign Twiddle_re_table_data[377] = 28'sb0011010110010111110000001000;
  assign Twiddle_re_table_data[378] = 28'sb0011010110001001111111111000;
  assign Twiddle_re_table_data[379] = 28'sb0011010101111100001101100011;
  assign Twiddle_re_table_data[380] = 28'sb0011010101101110011001001011;
  assign Twiddle_re_table_data[381] = 28'sb0011010101100000100010101111;
  assign Twiddle_re_table_data[382] = 28'sb0011010101010010101010001111;
  assign Twiddle_re_table_data[383] = 28'sb0011010101000100101111101100;
  assign Twiddle_re_table_data[384] = 28'sb0011010100110110110011000101;
  assign Twiddle_re_table_data[385] = 28'sb0011010100101000110100011011;
  assign Twiddle_re_table_data[386] = 28'sb0011010100011010110011101110;
  assign Twiddle_re_table_data[387] = 28'sb0011010100001100110000111110;
  assign Twiddle_re_table_data[388] = 28'sb0011010011111110101100001010;
  assign Twiddle_re_table_data[389] = 28'sb0011010011110000100101010100;
  assign Twiddle_re_table_data[390] = 28'sb0011010011100010011100011100;
  assign Twiddle_re_table_data[391] = 28'sb0011010011010100010001100001;
  assign Twiddle_re_table_data[392] = 28'sb0011010011000110000100100011;
  assign Twiddle_re_table_data[393] = 28'sb0011010010110111110101100100;
  assign Twiddle_re_table_data[394] = 28'sb0011010010101001100100100010;
  assign Twiddle_re_table_data[395] = 28'sb0011010010011011010001011110;
  assign Twiddle_re_table_data[396] = 28'sb0011010010001100111100011001;
  assign Twiddle_re_table_data[397] = 28'sb0011010001111110100101010010;
  assign Twiddle_re_table_data[398] = 28'sb0011010001110000001100001001;
  assign Twiddle_re_table_data[399] = 28'sb0011010001100001110000111111;
  assign Twiddle_re_table_data[400] = 28'sb0011010001010011010011110100;
  assign Twiddle_re_table_data[401] = 28'sb0011010001000100110100101000;
  assign Twiddle_re_table_data[402] = 28'sb0011010000110110010011011010;
  assign Twiddle_re_table_data[403] = 28'sb0011010000100111110000001100;
  assign Twiddle_re_table_data[404] = 28'sb0011010000011001001010111101;
  assign Twiddle_re_table_data[405] = 28'sb0011010000001010100011101110;
  assign Twiddle_re_table_data[406] = 28'sb0011001111111011111010011110;
  assign Twiddle_re_table_data[407] = 28'sb0011001111101101001111001110;
  assign Twiddle_re_table_data[408] = 28'sb0011001111011110100001111110;
  assign Twiddle_re_table_data[409] = 28'sb0011001111001111110010101110;
  assign Twiddle_re_table_data[410] = 28'sb0011001111000001000001011110;
  assign Twiddle_re_table_data[411] = 28'sb0011001110110010001110001110;
  assign Twiddle_re_table_data[412] = 28'sb0011001110100011011000111111;
  assign Twiddle_re_table_data[413] = 28'sb0011001110010100100001110000;
  assign Twiddle_re_table_data[414] = 28'sb0011001110000101101000100010;
  assign Twiddle_re_table_data[415] = 28'sb0011001101110110101101010101;
  assign Twiddle_re_table_data[416] = 28'sb0011001101100111110000001001;
  assign Twiddle_re_table_data[417] = 28'sb0011001101011000110000111110;
  assign Twiddle_re_table_data[418] = 28'sb0011001101001001101111110101;
  assign Twiddle_re_table_data[419] = 28'sb0011001100111010101100101100;
  assign Twiddle_re_table_data[420] = 28'sb0011001100101011100111100110;
  assign Twiddle_re_table_data[421] = 28'sb0011001100011100100000100001;
  assign Twiddle_re_table_data[422] = 28'sb0011001100001101010111011110;
  assign Twiddle_re_table_data[423] = 28'sb0011001011111110001100011101;
  assign Twiddle_re_table_data[424] = 28'sb0011001011101110111111011111;
  assign Twiddle_re_table_data[425] = 28'sb0011001011011111110000100010;
  assign Twiddle_re_table_data[426] = 28'sb0011001011010000011111101000;
  assign Twiddle_re_table_data[427] = 28'sb0011001011000001001100110001;
  assign Twiddle_re_table_data[428] = 28'sb0011001010110001110111111101;
  assign Twiddle_re_table_data[429] = 28'sb0011001010100010100001001011;
  assign Twiddle_re_table_data[430] = 28'sb0011001010010011001000011100;
  assign Twiddle_re_table_data[431] = 28'sb0011001010000011101101110001;
  assign Twiddle_re_table_data[432] = 28'sb0011001001110100010001001001;
  assign Twiddle_re_table_data[433] = 28'sb0011001001100100110010100101;
  assign Twiddle_re_table_data[434] = 28'sb0011001001010101010010000100;
  assign Twiddle_re_table_data[435] = 28'sb0011001001000101101111100111;
  assign Twiddle_re_table_data[436] = 28'sb0011001000110110001011001110;
  assign Twiddle_re_table_data[437] = 28'sb0011001000100110100100111001;
  assign Twiddle_re_table_data[438] = 28'sb0011001000010110111100101000;
  assign Twiddle_re_table_data[439] = 28'sb0011001000000111010010011100;
  assign Twiddle_re_table_data[440] = 28'sb0011000111110111100110010100;
  assign Twiddle_re_table_data[441] = 28'sb0011000111100111111000010010;
  assign Twiddle_re_table_data[442] = 28'sb0011000111011000001000010011;
  assign Twiddle_re_table_data[443] = 28'sb0011000111001000010110011010;
  assign Twiddle_re_table_data[444] = 28'sb0011000110111000100010100110;
  assign Twiddle_re_table_data[445] = 28'sb0011000110101000101100111000;
  assign Twiddle_re_table_data[446] = 28'sb0011000110011000110101001111;
  assign Twiddle_re_table_data[447] = 28'sb0011000110001000111011101011;
  assign Twiddle_re_table_data[448] = 28'sb0011000101111001000000001101;
  assign Twiddle_re_table_data[449] = 28'sb0011000101101001000010110110;
  assign Twiddle_re_table_data[450] = 28'sb0011000101011001000011100100;
  assign Twiddle_re_table_data[451] = 28'sb0011000101001001000010011000;
  assign Twiddle_re_table_data[452] = 28'sb0011000100111000111111010011;
  assign Twiddle_re_table_data[453] = 28'sb0011000100101000111010010101;
  assign Twiddle_re_table_data[454] = 28'sb0011000100011000110011011101;
  assign Twiddle_re_table_data[455] = 28'sb0011000100001000101010101100;
  assign Twiddle_re_table_data[456] = 28'sb0011000011111000100000000010;
  assign Twiddle_re_table_data[457] = 28'sb0011000011101000010011011111;
  assign Twiddle_re_table_data[458] = 28'sb0011000011011000000101000100;
  assign Twiddle_re_table_data[459] = 28'sb0011000011000111110100110000;
  assign Twiddle_re_table_data[460] = 28'sb0011000010110111100010100011;
  assign Twiddle_re_table_data[461] = 28'sb0011000010100111001110011111;
  assign Twiddle_re_table_data[462] = 28'sb0011000010010110111000100010;
  assign Twiddle_re_table_data[463] = 28'sb0011000010000110100000101110;
  assign Twiddle_re_table_data[464] = 28'sb0011000001110110000111000001;
  assign Twiddle_re_table_data[465] = 28'sb0011000001100101101011011110;
  assign Twiddle_re_table_data[466] = 28'sb0011000001010101001110000010;
  assign Twiddle_re_table_data[467] = 28'sb0011000001000100101110110000;
  assign Twiddle_re_table_data[468] = 28'sb0011000000110100001101100110;
  assign Twiddle_re_table_data[469] = 28'sb0011000000100011101010100110;
  assign Twiddle_re_table_data[470] = 28'sb0011000000010011000101101111;
  assign Twiddle_re_table_data[471] = 28'sb0011000000000010011111000001;
  assign Twiddle_re_table_data[472] = 28'sb0010111111110001110110011100;
  assign Twiddle_re_table_data[473] = 28'sb0010111111100001001100000010;
  assign Twiddle_re_table_data[474] = 28'sb0010111111010000011111110001;
  assign Twiddle_re_table_data[475] = 28'sb0010111110111111110001101010;
  assign Twiddle_re_table_data[476] = 28'sb0010111110101111000001101110;
  assign Twiddle_re_table_data[477] = 28'sb0010111110011110001111111011;
  assign Twiddle_re_table_data[478] = 28'sb0010111110001101011100010100;
  assign Twiddle_re_table_data[479] = 28'sb0010111101111100100110110111;
  assign Twiddle_re_table_data[480] = 28'sb0010111101101011101111100100;
  assign Twiddle_re_table_data[481] = 28'sb0010111101011010110110011101;
  assign Twiddle_re_table_data[482] = 28'sb0010111101001001111011100001;
  assign Twiddle_re_table_data[483] = 28'sb0010111100111000111110110000;
  assign Twiddle_re_table_data[484] = 28'sb0010111100101000000000001011;
  assign Twiddle_re_table_data[485] = 28'sb0010111100010110111111110001;
  assign Twiddle_re_table_data[486] = 28'sb0010111100000101111101100011;
  assign Twiddle_re_table_data[487] = 28'sb0010111011110100111001100010;
  assign Twiddle_re_table_data[488] = 28'sb0010111011100011110011101100;
  assign Twiddle_re_table_data[489] = 28'sb0010111011010010101100000010;
  assign Twiddle_re_table_data[490] = 28'sb0010111011000001100010100110;
  assign Twiddle_re_table_data[491] = 28'sb0010111010110000010111010101;
  assign Twiddle_re_table_data[492] = 28'sb0010111010011111001010010010;
  assign Twiddle_re_table_data[493] = 28'sb0010111010001101111011011011;
  assign Twiddle_re_table_data[494] = 28'sb0010111001111100101010110010;
  assign Twiddle_re_table_data[495] = 28'sb0010111001101011011000010110;
  assign Twiddle_re_table_data[496] = 28'sb0010111001011010000100000111;
  assign Twiddle_re_table_data[497] = 28'sb0010111001001000101110000110;
  assign Twiddle_re_table_data[498] = 28'sb0010111000110111010110010011;
  assign Twiddle_re_table_data[499] = 28'sb0010111000100101111100101110;
  assign Twiddle_re_table_data[500] = 28'sb0010111000010100100001010110;
  assign Twiddle_re_table_data[501] = 28'sb0010111000000011000100001110;
  assign Twiddle_re_table_data[502] = 28'sb0010110111110001100101010011;
  assign Twiddle_re_table_data[503] = 28'sb0010110111100000000100101000;
  assign Twiddle_re_table_data[504] = 28'sb0010110111001110100010001011;
  assign Twiddle_re_table_data[505] = 28'sb0010110110111100111101111101;
  assign Twiddle_re_table_data[506] = 28'sb0010110110101011010111111110;
  assign Twiddle_re_table_data[507] = 28'sb0010110110011001110000001110;
  assign Twiddle_re_table_data[508] = 28'sb0010110110001000000110101110;
  assign Twiddle_re_table_data[509] = 28'sb0010110101110110011011011110;
  assign Twiddle_re_table_data[510] = 28'sb0010110101100100101110011110;
  assign Twiddle_re_table_data[511] = 28'sb0010110101010010111111101101;
  assign twiddleS_re = Twiddle_re_table_data[twdlAddr];



  always @(posedge clk)
    begin : TWIDDLEROM_RE_process
      if (reset_x == 1'b0) begin
        twiddleReg_re <= 28'sb0000000000000000000000000000;
      end
      else begin
        if (enb) begin
          twiddleReg_re <= twiddleS_re;
        end
      end
    end



  // Twiddle ROM2
  assign Twiddle_im_table_data[0] = 28'sb0000000000000000000000000000;
  assign Twiddle_im_table_data[1] = 28'sb1111111111100110110111100000;
  assign Twiddle_im_table_data[2] = 28'sb1111111111001101101111000001;
  assign Twiddle_im_table_data[3] = 28'sb1111111110110100100110100010;
  assign Twiddle_im_table_data[4] = 28'sb1111111110011011011110000100;
  assign Twiddle_im_table_data[5] = 28'sb1111111110000010010101100111;
  assign Twiddle_im_table_data[6] = 28'sb1111111101101001001101001010;
  assign Twiddle_im_table_data[7] = 28'sb1111111101010000000100110000;
  assign Twiddle_im_table_data[8] = 28'sb1111111100110110111100010111;
  assign Twiddle_im_table_data[9] = 28'sb1111111100011101110100000000;
  assign Twiddle_im_table_data[10] = 28'sb1111111100000100101011101011;
  assign Twiddle_im_table_data[11] = 28'sb1111111011101011100011011001;
  assign Twiddle_im_table_data[12] = 28'sb1111111011010010011011001001;
  assign Twiddle_im_table_data[13] = 28'sb1111111010111001010010111100;
  assign Twiddle_im_table_data[14] = 28'sb1111111010100000001010110011;
  assign Twiddle_im_table_data[15] = 28'sb1111111010000111000010101101;
  assign Twiddle_im_table_data[16] = 28'sb1111111001101101111010101010;
  assign Twiddle_im_table_data[17] = 28'sb1111111001010100110010101011;
  assign Twiddle_im_table_data[18] = 28'sb1111111000111011101010110001;
  assign Twiddle_im_table_data[19] = 28'sb1111111000100010100010111010;
  assign Twiddle_im_table_data[20] = 28'sb1111111000001001011011001001;
  assign Twiddle_im_table_data[21] = 28'sb1111110111110000010011011100;
  assign Twiddle_im_table_data[22] = 28'sb1111110111010111001011110100;
  assign Twiddle_im_table_data[23] = 28'sb1111110110111110000100010010;
  assign Twiddle_im_table_data[24] = 28'sb1111110110100100111100110101;
  assign Twiddle_im_table_data[25] = 28'sb1111110110001011110101011110;
  assign Twiddle_im_table_data[26] = 28'sb1111110101110010101110001101;
  assign Twiddle_im_table_data[27] = 28'sb1111110101011001100111000010;
  assign Twiddle_im_table_data[28] = 28'sb1111110101000000011111111110;
  assign Twiddle_im_table_data[29] = 28'sb1111110100100111011001000001;
  assign Twiddle_im_table_data[30] = 28'sb1111110100001110010010001011;
  assign Twiddle_im_table_data[31] = 28'sb1111110011110101001011011100;
  assign Twiddle_im_table_data[32] = 28'sb1111110011011100000100110100;
  assign Twiddle_im_table_data[33] = 28'sb1111110011000010111110010100;
  assign Twiddle_im_table_data[34] = 28'sb1111110010101001110111111101;
  assign Twiddle_im_table_data[35] = 28'sb1111110010010000110001101101;
  assign Twiddle_im_table_data[36] = 28'sb1111110001110111101011100110;
  assign Twiddle_im_table_data[37] = 28'sb1111110001011110100101100111;
  assign Twiddle_im_table_data[38] = 28'sb1111110001000101011111110010;
  assign Twiddle_im_table_data[39] = 28'sb1111110000101100011010000110;
  assign Twiddle_im_table_data[40] = 28'sb1111110000010011010100100011;
  assign Twiddle_im_table_data[41] = 28'sb1111101111111010001111001010;
  assign Twiddle_im_table_data[42] = 28'sb1111101111100001001001111011;
  assign Twiddle_im_table_data[43] = 28'sb1111101111001000000100110110;
  assign Twiddle_im_table_data[44] = 28'sb1111101110101110111111111011;
  assign Twiddle_im_table_data[45] = 28'sb1111101110010101111011001011;
  assign Twiddle_im_table_data[46] = 28'sb1111101101111100110110100110;
  assign Twiddle_im_table_data[47] = 28'sb1111101101100011110010001100;
  assign Twiddle_im_table_data[48] = 28'sb1111101101001010101101111110;
  assign Twiddle_im_table_data[49] = 28'sb1111101100110001101001111011;
  assign Twiddle_im_table_data[50] = 28'sb1111101100011000100110000100;
  assign Twiddle_im_table_data[51] = 28'sb1111101011111111100010011001;
  assign Twiddle_im_table_data[52] = 28'sb1111101011100110011110111010;
  assign Twiddle_im_table_data[53] = 28'sb1111101011001101011011101000;
  assign Twiddle_im_table_data[54] = 28'sb1111101010110100011000100011;
  assign Twiddle_im_table_data[55] = 28'sb1111101010011011010101101011;
  assign Twiddle_im_table_data[56] = 28'sb1111101010000010010011000000;
  assign Twiddle_im_table_data[57] = 28'sb1111101001101001010000100011;
  assign Twiddle_im_table_data[58] = 28'sb1111101001010000001110010011;
  assign Twiddle_im_table_data[59] = 28'sb1111101000110111001100010010;
  assign Twiddle_im_table_data[60] = 28'sb1111101000011110001010011110;
  assign Twiddle_im_table_data[61] = 28'sb1111101000000101001000111010;
  assign Twiddle_im_table_data[62] = 28'sb1111100111101100000111100100;
  assign Twiddle_im_table_data[63] = 28'sb1111100111010011000110011101;
  assign Twiddle_im_table_data[64] = 28'sb1111100110111010000101100101;
  assign Twiddle_im_table_data[65] = 28'sb1111100110100001000100111101;
  assign Twiddle_im_table_data[66] = 28'sb1111100110001000000100100100;
  assign Twiddle_im_table_data[67] = 28'sb1111100101101111000100011100;
  assign Twiddle_im_table_data[68] = 28'sb1111100101010110000100100011;
  assign Twiddle_im_table_data[69] = 28'sb1111100100111101000100111100;
  assign Twiddle_im_table_data[70] = 28'sb1111100100100100000101100100;
  assign Twiddle_im_table_data[71] = 28'sb1111100100001011000110011110;
  assign Twiddle_im_table_data[72] = 28'sb1111100011110010000111101001;
  assign Twiddle_im_table_data[73] = 28'sb1111100011011001001001000101;
  assign Twiddle_im_table_data[74] = 28'sb1111100011000000001010110011;
  assign Twiddle_im_table_data[75] = 28'sb1111100010100111001100110011;
  assign Twiddle_im_table_data[76] = 28'sb1111100010001110001111000101;
  assign Twiddle_im_table_data[77] = 28'sb1111100001110101010001101001;
  assign Twiddle_im_table_data[78] = 28'sb1111100001011100010100100000;
  assign Twiddle_im_table_data[79] = 28'sb1111100001000011010111101010;
  assign Twiddle_im_table_data[80] = 28'sb1111100000101010011011000111;
  assign Twiddle_im_table_data[81] = 28'sb1111100000010001011110110111;
  assign Twiddle_im_table_data[82] = 28'sb1111011111111000100010111011;
  assign Twiddle_im_table_data[83] = 28'sb1111011111011111100111010010;
  assign Twiddle_im_table_data[84] = 28'sb1111011111000110101011111110;
  assign Twiddle_im_table_data[85] = 28'sb1111011110101101110000111110;
  assign Twiddle_im_table_data[86] = 28'sb1111011110010100110110010010;
  assign Twiddle_im_table_data[87] = 28'sb1111011101111011111011111011;
  assign Twiddle_im_table_data[88] = 28'sb1111011101100011000001111010;
  assign Twiddle_im_table_data[89] = 28'sb1111011101001010001000001101;
  assign Twiddle_im_table_data[90] = 28'sb1111011100110001001110110110;
  assign Twiddle_im_table_data[91] = 28'sb1111011100011000010101110101;
  assign Twiddle_im_table_data[92] = 28'sb1111011011111111011101001001;
  assign Twiddle_im_table_data[93] = 28'sb1111011011100110100100110100;
  assign Twiddle_im_table_data[94] = 28'sb1111011011001101101100110110;
  assign Twiddle_im_table_data[95] = 28'sb1111011010110100110101001110;
  assign Twiddle_im_table_data[96] = 28'sb1111011010011011111101111101;
  assign Twiddle_im_table_data[97] = 28'sb1111011010000011000111000011;
  assign Twiddle_im_table_data[98] = 28'sb1111011001101010010000100000;
  assign Twiddle_im_table_data[99] = 28'sb1111011001010001011010010101;
  assign Twiddle_im_table_data[100] = 28'sb1111011000111000100100100010;
  assign Twiddle_im_table_data[101] = 28'sb1111011000011111101111001000;
  assign Twiddle_im_table_data[102] = 28'sb1111011000000110111010000101;
  assign Twiddle_im_table_data[103] = 28'sb1111010111101110000101011011;
  assign Twiddle_im_table_data[104] = 28'sb1111010111010101010001001010;
  assign Twiddle_im_table_data[105] = 28'sb1111010110111100011101010011;
  assign Twiddle_im_table_data[106] = 28'sb1111010110100011101001110100;
  assign Twiddle_im_table_data[107] = 28'sb1111010110001010110110101111;
  assign Twiddle_im_table_data[108] = 28'sb1111010101110010000100000100;
  assign Twiddle_im_table_data[109] = 28'sb1111010101011001010001110011;
  assign Twiddle_im_table_data[110] = 28'sb1111010101000000011111111100;
  assign Twiddle_im_table_data[111] = 28'sb1111010100100111101110011111;
  assign Twiddle_im_table_data[112] = 28'sb1111010100001110111101011110;
  assign Twiddle_im_table_data[113] = 28'sb1111010011110110001100110111;
  assign Twiddle_im_table_data[114] = 28'sb1111010011011101011100101100;
  assign Twiddle_im_table_data[115] = 28'sb1111010011000100101100111100;
  assign Twiddle_im_table_data[116] = 28'sb1111010010101011111101101000;
  assign Twiddle_im_table_data[117] = 28'sb1111010010010011001110110000;
  assign Twiddle_im_table_data[118] = 28'sb1111010001111010100000010100;
  assign Twiddle_im_table_data[119] = 28'sb1111010001100001110010010100;
  assign Twiddle_im_table_data[120] = 28'sb1111010001001001000100110001;
  assign Twiddle_im_table_data[121] = 28'sb1111010000110000010111101011;
  assign Twiddle_im_table_data[122] = 28'sb1111010000010111101011000010;
  assign Twiddle_im_table_data[123] = 28'sb1111001111111110111110110111;
  assign Twiddle_im_table_data[124] = 28'sb1111001111100110010011001001;
  assign Twiddle_im_table_data[125] = 28'sb1111001111001101100111111001;
  assign Twiddle_im_table_data[126] = 28'sb1111001110110100111101000111;
  assign Twiddle_im_table_data[127] = 28'sb1111001110011100010010110011;
  assign Twiddle_im_table_data[128] = 28'sb1111001110000011101000111110;
  assign Twiddle_im_table_data[129] = 28'sb1111001101101010111111101000;
  assign Twiddle_im_table_data[130] = 28'sb1111001101010010010110110001;
  assign Twiddle_im_table_data[131] = 28'sb1111001100111001101110011001;
  assign Twiddle_im_table_data[132] = 28'sb1111001100100001000110100000;
  assign Twiddle_im_table_data[133] = 28'sb1111001100001000011111001000;
  assign Twiddle_im_table_data[134] = 28'sb1111001011101111111000001111;
  assign Twiddle_im_table_data[135] = 28'sb1111001011010111010001110111;
  assign Twiddle_im_table_data[136] = 28'sb1111001010111110101011111111;
  assign Twiddle_im_table_data[137] = 28'sb1111001010100110000110101000;
  assign Twiddle_im_table_data[138] = 28'sb1111001010001101100001110001;
  assign Twiddle_im_table_data[139] = 28'sb1111001001110100111101011100;
  assign Twiddle_im_table_data[140] = 28'sb1111001001011100011001101001;
  assign Twiddle_im_table_data[141] = 28'sb1111001001000011110110010110;
  assign Twiddle_im_table_data[142] = 28'sb1111001000101011010011100110;
  assign Twiddle_im_table_data[143] = 28'sb1111001000010010110001011000;
  assign Twiddle_im_table_data[144] = 28'sb1111000111111010001111101101;
  assign Twiddle_im_table_data[145] = 28'sb1111000111100001101110100100;
  assign Twiddle_im_table_data[146] = 28'sb1111000111001001001101111101;
  assign Twiddle_im_table_data[147] = 28'sb1111000110110000101101111010;
  assign Twiddle_im_table_data[148] = 28'sb1111000110011000001110011010;
  assign Twiddle_im_table_data[149] = 28'sb1111000101111111101111011110;
  assign Twiddle_im_table_data[150] = 28'sb1111000101100111010001000110;
  assign Twiddle_im_table_data[151] = 28'sb1111000101001110110011010001;
  assign Twiddle_im_table_data[152] = 28'sb1111000100110110010110000001;
  assign Twiddle_im_table_data[153] = 28'sb1111000100011101111001010101;
  assign Twiddle_im_table_data[154] = 28'sb1111000100000101011101001110;
  assign Twiddle_im_table_data[155] = 28'sb1111000011101101000001101100;
  assign Twiddle_im_table_data[156] = 28'sb1111000011010100100110101111;
  assign Twiddle_im_table_data[157] = 28'sb1111000010111100001100011000;
  assign Twiddle_im_table_data[158] = 28'sb1111000010100011110010100110;
  assign Twiddle_im_table_data[159] = 28'sb1111000010001011011001011010;
  assign Twiddle_im_table_data[160] = 28'sb1111000001110011000000110100;
  assign Twiddle_im_table_data[161] = 28'sb1111000001011010101000110101;
  assign Twiddle_im_table_data[162] = 28'sb1111000001000010010001011100;
  assign Twiddle_im_table_data[163] = 28'sb1111000000101001111010101010;
  assign Twiddle_im_table_data[164] = 28'sb1111000000010001100100011111;
  assign Twiddle_im_table_data[165] = 28'sb1110111111111001001110111100;
  assign Twiddle_im_table_data[166] = 28'sb1110111111100000111010000000;
  assign Twiddle_im_table_data[167] = 28'sb1110111111001000100101101011;
  assign Twiddle_im_table_data[168] = 28'sb1110111110110000010001111111;
  assign Twiddle_im_table_data[169] = 28'sb1110111110010111111110111011;
  assign Twiddle_im_table_data[170] = 28'sb1110111101111111101100100000;
  assign Twiddle_im_table_data[171] = 28'sb1110111101100111011010101101;
  assign Twiddle_im_table_data[172] = 28'sb1110111101001111001001100011;
  assign Twiddle_im_table_data[173] = 28'sb1110111100110110111001000010;
  assign Twiddle_im_table_data[174] = 28'sb1110111100011110101001001011;
  assign Twiddle_im_table_data[175] = 28'sb1110111100000110011001111110;
  assign Twiddle_im_table_data[176] = 28'sb1110111011101110001011011010;
  assign Twiddle_im_table_data[177] = 28'sb1110111011010101111101100000;
  assign Twiddle_im_table_data[178] = 28'sb1110111010111101110000010001;
  assign Twiddle_im_table_data[179] = 28'sb1110111010100101100011101100;
  assign Twiddle_im_table_data[180] = 28'sb1110111010001101010111110011;
  assign Twiddle_im_table_data[181] = 28'sb1110111001110101001100100100;
  assign Twiddle_im_table_data[182] = 28'sb1110111001011101000010000000;
  assign Twiddle_im_table_data[183] = 28'sb1110111001000100111000001000;
  assign Twiddle_im_table_data[184] = 28'sb1110111000101100101110111100;
  assign Twiddle_im_table_data[185] = 28'sb1110111000010100100110011100;
  assign Twiddle_im_table_data[186] = 28'sb1110110111111100011110101000;
  assign Twiddle_im_table_data[187] = 28'sb1110110111100100010111100000;
  assign Twiddle_im_table_data[188] = 28'sb1110110111001100010001000101;
  assign Twiddle_im_table_data[189] = 28'sb1110110110110100001011010111;
  assign Twiddle_im_table_data[190] = 28'sb1110110110011100000110010110;
  assign Twiddle_im_table_data[191] = 28'sb1110110110000100000010000011;
  assign Twiddle_im_table_data[192] = 28'sb1110110101101011111110011101;
  assign Twiddle_im_table_data[193] = 28'sb1110110101010011111011100101;
  assign Twiddle_im_table_data[194] = 28'sb1110110100111011111001011011;
  assign Twiddle_im_table_data[195] = 28'sb1110110100100011110111111111;
  assign Twiddle_im_table_data[196] = 28'sb1110110100001011110111010010;
  assign Twiddle_im_table_data[197] = 28'sb1110110011110011110111010100;
  assign Twiddle_im_table_data[198] = 28'sb1110110011011011111000000101;
  assign Twiddle_im_table_data[199] = 28'sb1110110011000011111001100100;
  assign Twiddle_im_table_data[200] = 28'sb1110110010101011111011110100;
  assign Twiddle_im_table_data[201] = 28'sb1110110010010011111110110011;
  assign Twiddle_im_table_data[202] = 28'sb1110110001111100000010100010;
  assign Twiddle_im_table_data[203] = 28'sb1110110001100100000111000001;
  assign Twiddle_im_table_data[204] = 28'sb1110110001001100001100010000;
  assign Twiddle_im_table_data[205] = 28'sb1110110000110100010010010000;
  assign Twiddle_im_table_data[206] = 28'sb1110110000011100011001000001;
  assign Twiddle_im_table_data[207] = 28'sb1110110000000100100000100011;
  assign Twiddle_im_table_data[208] = 28'sb1110101111101100101000110111;
  assign Twiddle_im_table_data[209] = 28'sb1110101111010100110001111100;
  assign Twiddle_im_table_data[210] = 28'sb1110101110111100111011110010;
  assign Twiddle_im_table_data[211] = 28'sb1110101110100101000110011011;
  assign Twiddle_im_table_data[212] = 28'sb1110101110001101010001110110;
  assign Twiddle_im_table_data[213] = 28'sb1110101101110101011110000011;
  assign Twiddle_im_table_data[214] = 28'sb1110101101011101101011000011;
  assign Twiddle_im_table_data[215] = 28'sb1110101101000101111000110110;
  assign Twiddle_im_table_data[216] = 28'sb1110101100101110000111011100;
  assign Twiddle_im_table_data[217] = 28'sb1110101100010110010110110101;
  assign Twiddle_im_table_data[218] = 28'sb1110101011111110100111000010;
  assign Twiddle_im_table_data[219] = 28'sb1110101011100110111000000011;
  assign Twiddle_im_table_data[220] = 28'sb1110101011001111001001111000;
  assign Twiddle_im_table_data[221] = 28'sb1110101010110111011100100001;
  assign Twiddle_im_table_data[222] = 28'sb1110101010011111101111111111;
  assign Twiddle_im_table_data[223] = 28'sb1110101010001000000100010001;
  assign Twiddle_im_table_data[224] = 28'sb1110101001110000011001011001;
  assign Twiddle_im_table_data[225] = 28'sb1110101001011000101111010101;
  assign Twiddle_im_table_data[226] = 28'sb1110101001000001000110000111;
  assign Twiddle_im_table_data[227] = 28'sb1110101000101001011101101111;
  assign Twiddle_im_table_data[228] = 28'sb1110101000010001110110001101;
  assign Twiddle_im_table_data[229] = 28'sb1110100111111010001111100000;
  assign Twiddle_im_table_data[230] = 28'sb1110100111100010101001101010;
  assign Twiddle_im_table_data[231] = 28'sb1110100111001011000100101011;
  assign Twiddle_im_table_data[232] = 28'sb1110100110110011100000100010;
  assign Twiddle_im_table_data[233] = 28'sb1110100110011011111101010001;
  assign Twiddle_im_table_data[234] = 28'sb1110100110000100011010110110;
  assign Twiddle_im_table_data[235] = 28'sb1110100101101100111001010011;
  assign Twiddle_im_table_data[236] = 28'sb1110100101010101011000101000;
  assign Twiddle_im_table_data[237] = 28'sb1110100100111101111000110101;
  assign Twiddle_im_table_data[238] = 28'sb1110100100100110011001111010;
  assign Twiddle_im_table_data[239] = 28'sb1110100100001110111011110111;
  assign Twiddle_im_table_data[240] = 28'sb1110100011110111011110101101;
  assign Twiddle_im_table_data[241] = 28'sb1110100011100000000010011100;
  assign Twiddle_im_table_data[242] = 28'sb1110100011001000100111000011;
  assign Twiddle_im_table_data[243] = 28'sb1110100010110001001100100100;
  assign Twiddle_im_table_data[244] = 28'sb1110100010011001110010111111;
  assign Twiddle_im_table_data[245] = 28'sb1110100010000010011010010011;
  assign Twiddle_im_table_data[246] = 28'sb1110100001101011000010100010;
  assign Twiddle_im_table_data[247] = 28'sb1110100001010011101011101010;
  assign Twiddle_im_table_data[248] = 28'sb1110100000111100010101101101;
  assign Twiddle_im_table_data[249] = 28'sb1110100000100101000000101010;
  assign Twiddle_im_table_data[250] = 28'sb1110100000001101101100100011;
  assign Twiddle_im_table_data[251] = 28'sb1110011111110110011001010110;
  assign Twiddle_im_table_data[252] = 28'sb1110011111011111000111000101;
  assign Twiddle_im_table_data[253] = 28'sb1110011111000111110101101111;
  assign Twiddle_im_table_data[254] = 28'sb1110011110110000100101010101;
  assign Twiddle_im_table_data[255] = 28'sb1110011110011001010101110111;
  assign Twiddle_im_table_data[256] = 28'sb1110011110000010000111010110;
  assign Twiddle_im_table_data[257] = 28'sb1110011101101010111001110000;
  assign Twiddle_im_table_data[258] = 28'sb1110011101010011101101001000;
  assign Twiddle_im_table_data[259] = 28'sb1110011100111100100001011100;
  assign Twiddle_im_table_data[260] = 28'sb1110011100100101010110101101;
  assign Twiddle_im_table_data[261] = 28'sb1110011100001110001100111100;
  assign Twiddle_im_table_data[262] = 28'sb1110011011110111000100001000;
  assign Twiddle_im_table_data[263] = 28'sb1110011011011111111100010010;
  assign Twiddle_im_table_data[264] = 28'sb1110011011001000110101011010;
  assign Twiddle_im_table_data[265] = 28'sb1110011010110001101111100000;
  assign Twiddle_im_table_data[266] = 28'sb1110011010011010101010100101;
  assign Twiddle_im_table_data[267] = 28'sb1110011010000011100110101000;
  assign Twiddle_im_table_data[268] = 28'sb1110011001101100100011101010;
  assign Twiddle_im_table_data[269] = 28'sb1110011001010101100001101011;
  assign Twiddle_im_table_data[270] = 28'sb1110011000111110100000101100;
  assign Twiddle_im_table_data[271] = 28'sb1110011000100111100000101100;
  assign Twiddle_im_table_data[272] = 28'sb1110011000010000100001101100;
  assign Twiddle_im_table_data[273] = 28'sb1110010111111001100011101100;
  assign Twiddle_im_table_data[274] = 28'sb1110010111100010100110101100;
  assign Twiddle_im_table_data[275] = 28'sb1110010111001011101010101100;
  assign Twiddle_im_table_data[276] = 28'sb1110010110110100101111101110;
  assign Twiddle_im_table_data[277] = 28'sb1110010110011101110101110000;
  assign Twiddle_im_table_data[278] = 28'sb1110010110000110111100110011;
  assign Twiddle_im_table_data[279] = 28'sb1110010101110000000100110111;
  assign Twiddle_im_table_data[280] = 28'sb1110010101011001001101111101;
  assign Twiddle_im_table_data[281] = 28'sb1110010101000010011000000101;
  assign Twiddle_im_table_data[282] = 28'sb1110010100101011100011001111;
  assign Twiddle_im_table_data[283] = 28'sb1110010100010100101111011011;
  assign Twiddle_im_table_data[284] = 28'sb1110010011111101111100101001;
  assign Twiddle_im_table_data[285] = 28'sb1110010011100111001010111010;
  assign Twiddle_im_table_data[286] = 28'sb1110010011010000011010001110;
  assign Twiddle_im_table_data[287] = 28'sb1110010010111001101010100101;
  assign Twiddle_im_table_data[288] = 28'sb1110010010100010111011111111;
  assign Twiddle_im_table_data[289] = 28'sb1110010010001100001110011101;
  assign Twiddle_im_table_data[290] = 28'sb1110010001110101100001111111;
  assign Twiddle_im_table_data[291] = 28'sb1110010001011110110110100100;
  assign Twiddle_im_table_data[292] = 28'sb1110010001001000001100001110;
  assign Twiddle_im_table_data[293] = 28'sb1110010000110001100010111100;
  assign Twiddle_im_table_data[294] = 28'sb1110010000011010111010101111;
  assign Twiddle_im_table_data[295] = 28'sb1110010000000100010011100110;
  assign Twiddle_im_table_data[296] = 28'sb1110001111101101101101100010;
  assign Twiddle_im_table_data[297] = 28'sb1110001111010111001000100100;
  assign Twiddle_im_table_data[298] = 28'sb1110001111000000100100101100;
  assign Twiddle_im_table_data[299] = 28'sb1110001110101010000001111001;
  assign Twiddle_im_table_data[300] = 28'sb1110001110010011100000001011;
  assign Twiddle_im_table_data[301] = 28'sb1110001101111100111111100100;
  assign Twiddle_im_table_data[302] = 28'sb1110001101100110100000000100;
  assign Twiddle_im_table_data[303] = 28'sb1110001101010000000001101010;
  assign Twiddle_im_table_data[304] = 28'sb1110001100111001100100010110;
  assign Twiddle_im_table_data[305] = 28'sb1110001100100011001000001010;
  assign Twiddle_im_table_data[306] = 28'sb1110001100001100101101000101;
  assign Twiddle_im_table_data[307] = 28'sb1110001011110110010011000111;
  assign Twiddle_im_table_data[308] = 28'sb1110001011011111111010010001;
  assign Twiddle_im_table_data[309] = 28'sb1110001011001001100010100011;
  assign Twiddle_im_table_data[310] = 28'sb1110001010110011001011111101;
  assign Twiddle_im_table_data[311] = 28'sb1110001010011100110110100000;
  assign Twiddle_im_table_data[312] = 28'sb1110001010000110100010001010;
  assign Twiddle_im_table_data[313] = 28'sb1110001001110000001110111110;
  assign Twiddle_im_table_data[314] = 28'sb1110001001011001111100111010;
  assign Twiddle_im_table_data[315] = 28'sb1110001001000011101100000000;
  assign Twiddle_im_table_data[316] = 28'sb1110001000101101011100001111;
  assign Twiddle_im_table_data[317] = 28'sb1110001000010111001101100111;
  assign Twiddle_im_table_data[318] = 28'sb1110001000000001000000001010;
  assign Twiddle_im_table_data[319] = 28'sb1110000111101010110011110110;
  assign Twiddle_im_table_data[320] = 28'sb1110000111010100101000101100;
  assign Twiddle_im_table_data[321] = 28'sb1110000110111110011110101110;
  assign Twiddle_im_table_data[322] = 28'sb1110000110101000010101111001;
  assign Twiddle_im_table_data[323] = 28'sb1110000110010010001110010000;
  assign Twiddle_im_table_data[324] = 28'sb1110000101111100000111110001;
  assign Twiddle_im_table_data[325] = 28'sb1110000101100110000010011110;
  assign Twiddle_im_table_data[326] = 28'sb1110000101001111111110010111;
  assign Twiddle_im_table_data[327] = 28'sb1110000100111001111011011011;
  assign Twiddle_im_table_data[328] = 28'sb1110000100100011111001101011;
  assign Twiddle_im_table_data[329] = 28'sb1110000100001101111001000111;
  assign Twiddle_im_table_data[330] = 28'sb1110000011110111111001110000;
  assign Twiddle_im_table_data[331] = 28'sb1110000011100001111011100101;
  assign Twiddle_im_table_data[332] = 28'sb1110000011001011111110100111;
  assign Twiddle_im_table_data[333] = 28'sb1110000010110110000010110110;
  assign Twiddle_im_table_data[334] = 28'sb1110000010100000001000010010;
  assign Twiddle_im_table_data[335] = 28'sb1110000010001010001110111011;
  assign Twiddle_im_table_data[336] = 28'sb1110000001110100010110110010;
  assign Twiddle_im_table_data[337] = 28'sb1110000001011110011111110111;
  assign Twiddle_im_table_data[338] = 28'sb1110000001001000101010001010;
  assign Twiddle_im_table_data[339] = 28'sb1110000000110010110101101100;
  assign Twiddle_im_table_data[340] = 28'sb1110000000011101000010011011;
  assign Twiddle_im_table_data[341] = 28'sb1110000000000111010000011010;
  assign Twiddle_im_table_data[342] = 28'sb1101111111110001011111100111;
  assign Twiddle_im_table_data[343] = 28'sb1101111111011011110000000011;
  assign Twiddle_im_table_data[344] = 28'sb1101111111000110000001101111;
  assign Twiddle_im_table_data[345] = 28'sb1101111110110000010100101010;
  assign Twiddle_im_table_data[346] = 28'sb1101111110011010101000110101;
  assign Twiddle_im_table_data[347] = 28'sb1101111110000100111110010000;
  assign Twiddle_im_table_data[348] = 28'sb1101111101101111010100111011;
  assign Twiddle_im_table_data[349] = 28'sb1101111101011001101100110111;
  assign Twiddle_im_table_data[350] = 28'sb1101111101000100000110000010;
  assign Twiddle_im_table_data[351] = 28'sb1101111100101110100000011111;
  assign Twiddle_im_table_data[352] = 28'sb1101111100011000111100001101;
  assign Twiddle_im_table_data[353] = 28'sb1101111100000011011001001100;
  assign Twiddle_im_table_data[354] = 28'sb1101111011101101110111011100;
  assign Twiddle_im_table_data[355] = 28'sb1101111011011000010110111110;
  assign Twiddle_im_table_data[356] = 28'sb1101111011000010110111110001;
  assign Twiddle_im_table_data[357] = 28'sb1101111010101101011001110111;
  assign Twiddle_im_table_data[358] = 28'sb1101111010010111111101001111;
  assign Twiddle_im_table_data[359] = 28'sb1101111010000010100001111001;
  assign Twiddle_im_table_data[360] = 28'sb1101111001101101000111110110;
  assign Twiddle_im_table_data[361] = 28'sb1101111001010111101111000110;
  assign Twiddle_im_table_data[362] = 28'sb1101111001000010010111101001;
  assign Twiddle_im_table_data[363] = 28'sb1101111000101101000001011111;
  assign Twiddle_im_table_data[364] = 28'sb1101111000010111101100101001;
  assign Twiddle_im_table_data[365] = 28'sb1101111000000010011001000110;
  assign Twiddle_im_table_data[366] = 28'sb1101110111101101000110110111;
  assign Twiddle_im_table_data[367] = 28'sb1101110111010111110101111100;
  assign Twiddle_im_table_data[368] = 28'sb1101110111000010100110010101;
  assign Twiddle_im_table_data[369] = 28'sb1101110110101101011000000011;
  assign Twiddle_im_table_data[370] = 28'sb1101110110011000001011000110;
  assign Twiddle_im_table_data[371] = 28'sb1101110110000010111111011110;
  assign Twiddle_im_table_data[372] = 28'sb1101110101101101110101001010;
  assign Twiddle_im_table_data[373] = 28'sb1101110101011000101100001100;
  assign Twiddle_im_table_data[374] = 28'sb1101110101000011100100100011;
  assign Twiddle_im_table_data[375] = 28'sb1101110100101110011110010000;
  assign Twiddle_im_table_data[376] = 28'sb1101110100011001011001010100;
  assign Twiddle_im_table_data[377] = 28'sb1101110100000100010101101101;
  assign Twiddle_im_table_data[378] = 28'sb1101110011101111010011011100;
  assign Twiddle_im_table_data[379] = 28'sb1101110011011010010010100010;
  assign Twiddle_im_table_data[380] = 28'sb1101110011000101010010111111;
  assign Twiddle_im_table_data[381] = 28'sb1101110010110000010100110010;
  assign Twiddle_im_table_data[382] = 28'sb1101110010011011010111111101;
  assign Twiddle_im_table_data[383] = 28'sb1101110010000110011100011111;
  assign Twiddle_im_table_data[384] = 28'sb1101110001110001100010011001;
  assign Twiddle_im_table_data[385] = 28'sb1101110001011100101001101010;
  assign Twiddle_im_table_data[386] = 28'sb1101110001000111110010010011;
  assign Twiddle_im_table_data[387] = 28'sb1101110000110010111100010101;
  assign Twiddle_im_table_data[388] = 28'sb1101110000011110000111101111;
  assign Twiddle_im_table_data[389] = 28'sb1101110000001001010100100001;
  assign Twiddle_im_table_data[390] = 28'sb1101101111110100100010101100;
  assign Twiddle_im_table_data[391] = 28'sb1101101111011111110010010000;
  assign Twiddle_im_table_data[392] = 28'sb1101101111001011000011001101;
  assign Twiddle_im_table_data[393] = 28'sb1101101110110110010101100011;
  assign Twiddle_im_table_data[394] = 28'sb1101101110100001101001010011;
  assign Twiddle_im_table_data[395] = 28'sb1101101110001100111110011101;
  assign Twiddle_im_table_data[396] = 28'sb1101101101111000010101000001;
  assign Twiddle_im_table_data[397] = 28'sb1101101101100011101100111110;
  assign Twiddle_im_table_data[398] = 28'sb1101101101001111000110010110;
  assign Twiddle_im_table_data[399] = 28'sb1101101100111010100001001001;
  assign Twiddle_im_table_data[400] = 28'sb1101101100100101111101010110;
  assign Twiddle_im_table_data[401] = 28'sb1101101100010001011010111111;
  assign Twiddle_im_table_data[402] = 28'sb1101101011111100111010000010;
  assign Twiddle_im_table_data[403] = 28'sb1101101011101000011010100001;
  assign Twiddle_im_table_data[404] = 28'sb1101101011010011111100011011;
  assign Twiddle_im_table_data[405] = 28'sb1101101010111111011111110001;
  assign Twiddle_im_table_data[406] = 28'sb1101101010101011000100100011;
  assign Twiddle_im_table_data[407] = 28'sb1101101010010110101010110001;
  assign Twiddle_im_table_data[408] = 28'sb1101101010000010010010011011;
  assign Twiddle_im_table_data[409] = 28'sb1101101001101101111011100010;
  assign Twiddle_im_table_data[410] = 28'sb1101101001011001100110000110;
  assign Twiddle_im_table_data[411] = 28'sb1101101001000101010010000110;
  assign Twiddle_im_table_data[412] = 28'sb1101101000110000111111100100;
  assign Twiddle_im_table_data[413] = 28'sb1101101000011100101110011110;
  assign Twiddle_im_table_data[414] = 28'sb1101101000001000011110110111;
  assign Twiddle_im_table_data[415] = 28'sb1101100111110100010000101101;
  assign Twiddle_im_table_data[416] = 28'sb1101100111100000000100000000;
  assign Twiddle_im_table_data[417] = 28'sb1101100111001011111000110010;
  assign Twiddle_im_table_data[418] = 28'sb1101100110110111101111000010;
  assign Twiddle_im_table_data[419] = 28'sb1101100110100011100110110001;
  assign Twiddle_im_table_data[420] = 28'sb1101100110001111011111111110;
  assign Twiddle_im_table_data[421] = 28'sb1101100101111011011010101010;
  assign Twiddle_im_table_data[422] = 28'sb1101100101100111010110110110;
  assign Twiddle_im_table_data[423] = 28'sb1101100101010011010100100000;
  assign Twiddle_im_table_data[424] = 28'sb1101100100111111010011101010;
  assign Twiddle_im_table_data[425] = 28'sb1101100100101011010100010011;
  assign Twiddle_im_table_data[426] = 28'sb1101100100010111010110011101;
  assign Twiddle_im_table_data[427] = 28'sb1101100100000011011010000110;
  assign Twiddle_im_table_data[428] = 28'sb1101100011101111011111001111;
  assign Twiddle_im_table_data[429] = 28'sb1101100011011011100101111001;
  assign Twiddle_im_table_data[430] = 28'sb1101100011000111101110000100;
  assign Twiddle_im_table_data[431] = 28'sb1101100010110011110111101111;
  assign Twiddle_im_table_data[432] = 28'sb1101100010100000000010111011;
  assign Twiddle_im_table_data[433] = 28'sb1101100010001100001111101000;
  assign Twiddle_im_table_data[434] = 28'sb1101100001111000011101110111;
  assign Twiddle_im_table_data[435] = 28'sb1101100001100100101101100111;
  assign Twiddle_im_table_data[436] = 28'sb1101100001010000111110111001;
  assign Twiddle_im_table_data[437] = 28'sb1101100000111101010001101101;
  assign Twiddle_im_table_data[438] = 28'sb1101100000101001100110000011;
  assign Twiddle_im_table_data[439] = 28'sb1101100000010101111011111011;
  assign Twiddle_im_table_data[440] = 28'sb1101100000000010010011010110;
  assign Twiddle_im_table_data[441] = 28'sb1101011111101110101100010011;
  assign Twiddle_im_table_data[442] = 28'sb1101011111011011000110110011;
  assign Twiddle_im_table_data[443] = 28'sb1101011111000111100010110111;
  assign Twiddle_im_table_data[444] = 28'sb1101011110110100000000011101;
  assign Twiddle_im_table_data[445] = 28'sb1101011110100000011111100111;
  assign Twiddle_im_table_data[446] = 28'sb1101011110001101000000010101;
  assign Twiddle_im_table_data[447] = 28'sb1101011101111001100010100110;
  assign Twiddle_im_table_data[448] = 28'sb1101011101100110000110011011;
  assign Twiddle_im_table_data[449] = 28'sb1101011101010010101011110101;
  assign Twiddle_im_table_data[450] = 28'sb1101011100111111010010110011;
  assign Twiddle_im_table_data[451] = 28'sb1101011100101011111011010101;
  assign Twiddle_im_table_data[452] = 28'sb1101011100011000100101011101;
  assign Twiddle_im_table_data[453] = 28'sb1101011100000101010001001001;
  assign Twiddle_im_table_data[454] = 28'sb1101011011110001111110011010;
  assign Twiddle_im_table_data[455] = 28'sb1101011011011110101101010001;
  assign Twiddle_im_table_data[456] = 28'sb1101011011001011011101101101;
  assign Twiddle_im_table_data[457] = 28'sb1101011010111000001111101110;
  assign Twiddle_im_table_data[458] = 28'sb1101011010100101000011010110;
  assign Twiddle_im_table_data[459] = 28'sb1101011010010001111000100011;
  assign Twiddle_im_table_data[460] = 28'sb1101011001111110101111010111;
  assign Twiddle_im_table_data[461] = 28'sb1101011001101011100111110001;
  assign Twiddle_im_table_data[462] = 28'sb1101011001011000100001110010;
  assign Twiddle_im_table_data[463] = 28'sb1101011001000101011101011010;
  assign Twiddle_im_table_data[464] = 28'sb1101011000110010011010101001;
  assign Twiddle_im_table_data[465] = 28'sb1101011000011111011001011110;
  assign Twiddle_im_table_data[466] = 28'sb1101011000001100011001111011;
  assign Twiddle_im_table_data[467] = 28'sb1101010111111001011100000000;
  assign Twiddle_im_table_data[468] = 28'sb1101010111100110011111101100;
  assign Twiddle_im_table_data[469] = 28'sb1101010111010011100101000000;
  assign Twiddle_im_table_data[470] = 28'sb1101010111000000101011111100;
  assign Twiddle_im_table_data[471] = 28'sb1101010110101101110100100001;
  assign Twiddle_im_table_data[472] = 28'sb1101010110011010111110101110;
  assign Twiddle_im_table_data[473] = 28'sb1101010110001000001010100011;
  assign Twiddle_im_table_data[474] = 28'sb1101010101110101011000000001;
  assign Twiddle_im_table_data[475] = 28'sb1101010101100010100111001001;
  assign Twiddle_im_table_data[476] = 28'sb1101010101001111110111111001;
  assign Twiddle_im_table_data[477] = 28'sb1101010100111101001010010011;
  assign Twiddle_im_table_data[478] = 28'sb1101010100101010011110010110;
  assign Twiddle_im_table_data[479] = 28'sb1101010100010111110100000011;
  assign Twiddle_im_table_data[480] = 28'sb1101010100000101001011011001;
  assign Twiddle_im_table_data[481] = 28'sb1101010011110010100100011010;
  assign Twiddle_im_table_data[482] = 28'sb1101010011011111111111000101;
  assign Twiddle_im_table_data[483] = 28'sb1101010011001101011011011011;
  assign Twiddle_im_table_data[484] = 28'sb1101010010111010111001011011;
  assign Twiddle_im_table_data[485] = 28'sb1101010010101000011001000101;
  assign Twiddle_im_table_data[486] = 28'sb1101010010010101111010011011;
  assign Twiddle_im_table_data[487] = 28'sb1101010010000011011101011100;
  assign Twiddle_im_table_data[488] = 28'sb1101010001110001000010001000;
  assign Twiddle_im_table_data[489] = 28'sb1101010001011110101000100000;
  assign Twiddle_im_table_data[490] = 28'sb1101010001001100010000100011;
  assign Twiddle_im_table_data[491] = 28'sb1101010000111001111010010010;
  assign Twiddle_im_table_data[492] = 28'sb1101010000100111100101101101;
  assign Twiddle_im_table_data[493] = 28'sb1101010000010101010010110101;
  assign Twiddle_im_table_data[494] = 28'sb1101010000000011000001101000;
  assign Twiddle_im_table_data[495] = 28'sb1101001111110000110010001000;
  assign Twiddle_im_table_data[496] = 28'sb1101001111011110100100010101;
  assign Twiddle_im_table_data[497] = 28'sb1101001111001100011000001111;
  assign Twiddle_im_table_data[498] = 28'sb1101001110111010001101110110;
  assign Twiddle_im_table_data[499] = 28'sb1101001110101000000101001010;
  assign Twiddle_im_table_data[500] = 28'sb1101001110010101111110001100;
  assign Twiddle_im_table_data[501] = 28'sb1101001110000011111000111011;
  assign Twiddle_im_table_data[502] = 28'sb1101001101110001110101011000;
  assign Twiddle_im_table_data[503] = 28'sb1101001101011111110011100010;
  assign Twiddle_im_table_data[504] = 28'sb1101001101001101110011011011;
  assign Twiddle_im_table_data[505] = 28'sb1101001100111011110101000010;
  assign Twiddle_im_table_data[506] = 28'sb1101001100101001111000011000;
  assign Twiddle_im_table_data[507] = 28'sb1101001100010111111101011100;
  assign Twiddle_im_table_data[508] = 28'sb1101001100000110000100001111;
  assign Twiddle_im_table_data[509] = 28'sb1101001011110100001100110001;
  assign Twiddle_im_table_data[510] = 28'sb1101001011100010010111000011;
  assign Twiddle_im_table_data[511] = 28'sb1101001011010000100011000011;
  assign twiddleS_im = Twiddle_im_table_data[twdlAddr];



  always @(posedge clk)
    begin : TWIDDLEROM_IM_process
      if (reset_x == 1'b0) begin
        twiddleReg_im <= 28'sb0000000000000000000000000000;
      end
      else begin
        if (enb) begin
          twiddleReg_im <= twiddleS_im;
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_process
      if (reset_x == 1'b0) begin
        twdlOctantReg <= 3'b000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            twdlOctantReg <= 3'b000;
          end
          else begin
            twdlOctantReg <= twdlOctant;
          end
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_1_process
      if (reset_x == 1'b0) begin
        twdl45Reg <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            twdl45Reg <= 1'b0;
          end
          else begin
            twdl45Reg <= twdl45;
          end
        end
      end
    end



  // Radix22TwdlOctCorr
  always @(twdl45Reg, twdlOctantReg, twiddleReg_im, twiddleReg_re) begin
    Radix22TwdlOctCorr_cast_0 = 29'sb00000000000000000000000000000;
    Radix22TwdlOctCorr_cast_2 = 29'sb00000000000000000000000000000;
    Radix22TwdlOctCorr_cast_4 = 29'sb00000000000000000000000000000;
    Radix22TwdlOctCorr_cast_6 = 29'sb00000000000000000000000000000;
    Radix22TwdlOctCorr_cast_8 = 29'sb00000000000000000000000000000;
    Radix22TwdlOctCorr_cast_10 = 29'sb00000000000000000000000000000;
    Radix22TwdlOctCorr_cast_3 = 29'sb00000000000000000000000000000;
    Radix22TwdlOctCorr_cast_9 = 29'sb00000000000000000000000000000;
    Radix22TwdlOctCorr_cast_1 = 29'sb00000000000000000000000000000;
    Radix22TwdlOctCorr_cast_7 = 29'sb00000000000000000000000000000;
    Radix22TwdlOctCorr_cast = 29'sb00000000000000000000000000000;
    Radix22TwdlOctCorr_cast_5 = 29'sb00000000000000000000000000000;
    Radix22TwdlOctCorr_twdlIn_re = twiddleReg_re;
    Radix22TwdlOctCorr_twdlIn_im = twiddleReg_im;
    if (twdl45Reg) begin
      case ( twdlOctantReg)
        3'b000 :
          begin
            Radix22TwdlOctCorr_twdlIn_re = 28'sb0010110101000001001111001101;
            Radix22TwdlOctCorr_twdlIn_im = 28'sb1101001010111110110000110011;
          end
        3'b010 :
          begin
            Radix22TwdlOctCorr_twdlIn_re = 28'sb1101001010111110110000110011;
            Radix22TwdlOctCorr_twdlIn_im = 28'sb1101001010111110110000110011;
          end
        3'b100 :
          begin
            Radix22TwdlOctCorr_twdlIn_re = 28'sb1101001010111110110000110011;
            Radix22TwdlOctCorr_twdlIn_im = 28'sb0010110101000001001111001101;
          end
        default :
          begin
            Radix22TwdlOctCorr_twdlIn_re = 28'sb0010110101000001001111001101;
            Radix22TwdlOctCorr_twdlIn_im = 28'sb1101001010111110110000110011;
          end
      endcase
    end
    else begin
      case ( twdlOctantReg)
        3'b000 :
          begin
          end
        3'b001 :
          begin
            Radix22TwdlOctCorr_cast = {twiddleReg_im[27], twiddleReg_im};
            Radix22TwdlOctCorr_cast_0 =  - (Radix22TwdlOctCorr_cast);
            Radix22TwdlOctCorr_twdlIn_re = Radix22TwdlOctCorr_cast_0[27:0];
            Radix22TwdlOctCorr_cast_5 = {twiddleReg_re[27], twiddleReg_re};
            Radix22TwdlOctCorr_cast_6 =  - (Radix22TwdlOctCorr_cast_5);
            Radix22TwdlOctCorr_twdlIn_im = Radix22TwdlOctCorr_cast_6[27:0];
          end
        3'b010 :
          begin
            Radix22TwdlOctCorr_twdlIn_re = twiddleReg_im;
            Radix22TwdlOctCorr_cast_7 = {twiddleReg_re[27], twiddleReg_re};
            Radix22TwdlOctCorr_cast_8 =  - (Radix22TwdlOctCorr_cast_7);
            Radix22TwdlOctCorr_twdlIn_im = Radix22TwdlOctCorr_cast_8[27:0];
          end
        3'b011 :
          begin
            Radix22TwdlOctCorr_cast_1 = {twiddleReg_re[27], twiddleReg_re};
            Radix22TwdlOctCorr_cast_2 =  - (Radix22TwdlOctCorr_cast_1);
            Radix22TwdlOctCorr_twdlIn_re = Radix22TwdlOctCorr_cast_2[27:0];
            Radix22TwdlOctCorr_twdlIn_im = twiddleReg_im;
          end
        3'b100 :
          begin
            Radix22TwdlOctCorr_cast_3 = {twiddleReg_re[27], twiddleReg_re};
            Radix22TwdlOctCorr_cast_4 =  - (Radix22TwdlOctCorr_cast_3);
            Radix22TwdlOctCorr_twdlIn_re = Radix22TwdlOctCorr_cast_4[27:0];
            Radix22TwdlOctCorr_cast_9 = {twiddleReg_im[27], twiddleReg_im};
            Radix22TwdlOctCorr_cast_10 =  - (Radix22TwdlOctCorr_cast_9);
            Radix22TwdlOctCorr_twdlIn_im = Radix22TwdlOctCorr_cast_10[27:0];
          end
        default :
          begin
            Radix22TwdlOctCorr_twdlIn_re = twiddleReg_im;
            Radix22TwdlOctCorr_twdlIn_im = twiddleReg_re;
          end
      endcase
    end
    twdl_re_1 = Radix22TwdlOctCorr_twdlIn_re;
    twdl_im_1 = Radix22TwdlOctCorr_twdlIn_im;
  end



  assign twdl_vld = 1'b0;



  assign twdl_re = twdl_re_1;

  assign twdl_im = twdl_im_1;

endmodule  // TWDLROM

