// -------------------------------------------------------------
// 
// File Name: DUAL_port_RAM_and_GA3\hdlsrc\DUALportRAMinterface_v3\a4_random.v
// Created: 2024-05-04 07:38:48
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: a4_random
// Source Path: DUALportRAMinterface_v3/PL/integration_block1/Subsystem/a4_random
// Hierarchy Level: 3
// Model version: 1.38
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module a4_random
          (clk,
           reset_x,
           enb,
           In1,
           In2,
           Out1);


  input   clk;
  input   reset_x;
  input   enb;
  input   [15:0] In1;  // uint16
  input   In2;
  output  signed [17:0] Out1;  // sfix18_En15


  wire [31:0] Data_Type_Conversion7_out1;  // ufix32_En16
  wire [31:0] Bit_Shift2_out1;  // ufix32_En16
  wire [10:0] Data_Type_Conversion6_out1;  // ufix11_En11
  wire Constant_out1deadIn;
  wire [50:0] Modulo_by_Constant_HDL_Optimized_out1;  // ufix51_En57
  wire Modulo_by_Constant_HDL_Optimized_out2deadOut;
  wire signed [16:0] Data_Type_Conversion8_out1;  // sfix17_En15
  wire switch_compare_1;
  wire signed [16:0] Add5_out1;  // sfix17_En15
  wire signed [17:0] Add5_out1_dtc;  // sfix18_En15
  wire signed [18:0] Add4_sub_cast;  // sfix19_En15
  wire signed [18:0] Add4_sub_temp;  // sfix19_En15
  wire signed [17:0] Add4_out1;  // sfix18_En15
  wire signed [17:0] Switch2_out1;  // sfix18_En15


  assign Data_Type_Conversion7_out1 = {In1, 16'b0000000000000000};



  assign Bit_Shift2_out1 = Data_Type_Conversion7_out1 >> 8'd22;



  assign Data_Type_Conversion6_out1 = Bit_Shift2_out1[15:5];



  assign Constant_out1deadIn = 1'b0;



  modimpl_ntwk_block1 u_mod_by_constant (.clk(clk),
                                         .reset_x(reset_x),
                                         .enb(enb),
                                         .X(Data_Type_Conversion6_out1),  // ufix11_En11
                                         .validIn(Constant_out1deadIn),
                                         .Y(Modulo_by_Constant_HDL_Optimized_out1),  // ufix51_En57
                                         .validOut(Modulo_by_Constant_HDL_Optimized_out2deadOut)
                                         );

  assign Data_Type_Conversion8_out1 = {8'b0, Modulo_by_Constant_HDL_Optimized_out1[50:42]};



  assign switch_compare_1 = In2 > 1'b0;



  assign Add5_out1 = Data_Type_Conversion8_out1 + 17'sb11111101011100001;



  assign Add5_out1_dtc = {Add5_out1[16], Add5_out1};



  assign Add4_sub_cast = {{2{Data_Type_Conversion8_out1[16]}}, Data_Type_Conversion8_out1};
  assign Add4_sub_temp = 19'sb1111111101011100001 - Add4_sub_cast;
  assign Add4_out1 = Add4_sub_temp[17:0];



  assign Switch2_out1 = (switch_compare_1 == 1'b0 ? Add5_out1_dtc :
              Add4_out1);



  assign Out1 = Switch2_out1;

endmodule  // a4_random

