// -------------------------------------------------------------
// 
// File Name: DUAL_port_RAM_and_GA3\hdlsrc\DUALportRAMinterface_v3\FFT.v
// Created: 2024-05-04 07:38:48
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FFT
// Source Path: DUALportRAMinterface_v3/PL/integration_block1/FFT
// Hierarchy Level: 2
// Model version: 1.38
// 
// FFT
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FFT
          (clk,
           reset_x,
           enb,
           dataIn,
           validIn,
           syncReset,
           dataOut_re,
           dataOut_im,
           validOut,
           ready);


  input   clk;
  input   reset_x;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En14
  input   validIn;
  input   syncReset;
  output  signed [27:0] dataOut_re;  // sfix28_En14
  output  signed [27:0] dataOut_im;  // sfix28_En14
  output  validOut;
  output  ready;


  wire signed [27:0] dtc_re;  // sfix28_En14
  wire signed [27:0] dtc_im;  // sfix28_En14
  wire dMemOut_vld;
  reg  dMemOutDly_vld;
  wire [3:0] stage;  // ufix4
  wire initIC;
  wire signed [27:0] twdl_re;  // sfix28_En26
  wire signed [27:0] twdl_im;  // sfix28_En26
  wire twdl_vlddeadOut;
  wire signed [27:0] dMemIn1_re;  // sfix28_En14
  wire signed [27:0] dMemIn1_im;  // sfix28_En14
  wire signed [27:0] dMemIn2_re;  // sfix28_En14
  wire signed [27:0] dMemIn2_im;  // sfix28_En14
  wire wrEnb1;
  wire wrEnb2;
  wire wrEnb3;
  wire rdEnb1;
  wire rdEnb2;
  wire rdEnb3;
  wire unLoadPhase;
  wire signed [27:0] dMemOut1_re;  // sfix28_En14
  wire signed [27:0] dMemOut1_im;  // sfix28_En14
  wire signed [27:0] dMemOut2_re;  // sfix28_En14
  wire signed [27:0] dMemOut2_im;  // sfix28_En14
  wire rdy;
  wire signed [27:0] btfIn1_re;  // sfix28_En14
  wire signed [27:0] btfIn1_im;  // sfix28_En14
  wire signed [27:0] btfIn2_re;  // sfix28_En14
  wire signed [27:0] btfIn2_im;  // sfix28_En14
  wire btfIn_vld;
  wire signed [27:0] btfOut1_re;  // sfix28_En14
  wire signed [27:0] btfOut1_im;  // sfix28_En14
  wire signed [27:0] btfOut2_re;  // sfix28_En14
  wire signed [27:0] btfOut2_im;  // sfix28_En14
  wire btfOut_vld;
  wire signed [27:0] stgOut1_re;  // sfix28_En14
  wire signed [27:0] stgOut1_im;  // sfix28_En14
  wire signed [27:0] stgOut2_re;  // sfix28_En14
  wire signed [27:0] stgOut2_im;  // sfix28_En14
  wire stgOut_vld;
  wire vldOut;
  wire signed [27:0] dOut_re;  // sfix28_En14
  wire signed [27:0] dOut_im;  // sfix28_En14
  wire dout_vld;


  assign dtc_re = {{12{dataIn[15]}}, dataIn};



  assign dtc_im = 28'sb0000000000000000000000000000;



  always @(posedge clk)
    begin : intdelay_process
      if (reset_x == 1'b0) begin
        dMemOutDly_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dMemOutDly_vld <= 1'b0;
          end
          else begin
            dMemOutDly_vld <= dMemOut_vld;
          end
        end
      end
    end



  TWDLROM u_MinResRX2FFT_TWDLROM (.clk(clk),
                                  .reset_x(reset_x),
                                  .enb(enb),
                                  .dMemOutDly_vld(dMemOutDly_vld),
                                  .stage(stage),  // ufix4
                                  .initIC(initIC),
                                  .syncReset(syncReset),
                                  .twdl_re(twdl_re),  // sfix28_En26
                                  .twdl_im(twdl_im),  // sfix28_En26
                                  .twdl_vld(twdl_vlddeadOut)
                                  );

  MINRESRX2FFT_MEMORY u_MinResRX2FFT_MEMORY (.clk(clk),
                                             .reset_x(reset_x),
                                             .enb(enb),
                                             .dMemIn1_re(dMemIn1_re),  // sfix28_En14
                                             .dMemIn1_im(dMemIn1_im),  // sfix28_En14
                                             .dMemIn2_re(dMemIn2_re),  // sfix28_En14
                                             .dMemIn2_im(dMemIn2_im),  // sfix28_En14
                                             .wrEnb1(wrEnb1),
                                             .wrEnb2(wrEnb2),
                                             .wrEnb3(wrEnb3),
                                             .rdEnb1(rdEnb1),
                                             .rdEnb2(rdEnb2),
                                             .rdEnb3(rdEnb3),
                                             .stage(stage),  // ufix4
                                             .initIC(initIC),
                                             .unLoadPhase(unLoadPhase),
                                             .syncReset(syncReset),
                                             .dMemOut1_re(dMemOut1_re),  // sfix28_En14
                                             .dMemOut1_im(dMemOut1_im),  // sfix28_En14
                                             .dMemOut2_re(dMemOut2_re),  // sfix28_En14
                                             .dMemOut2_im(dMemOut2_im)  // sfix28_En14
                                             );

  MINRESRX2FFT_BTFSEL u_MinResRX2FFT_BTFSEL (.clk(clk),
                                             .reset_x(reset_x),
                                             .enb(enb),
                                             .din_1_re(dtc_re),  // sfix28_En14
                                             .din_1_im(dtc_im),  // sfix28_En14
                                             .validIn(validIn),
                                             .rdy(rdy),
                                             .dMemOut1_re(dMemOut1_re),  // sfix28_En14
                                             .dMemOut1_im(dMemOut1_im),  // sfix28_En14
                                             .dMemOut2_re(dMemOut2_re),  // sfix28_En14
                                             .dMemOut2_im(dMemOut2_im),  // sfix28_En14
                                             .dMemOut_vld(dMemOut_vld),
                                             .stage(stage),  // ufix4
                                             .initIC(initIC),
                                             .syncReset(syncReset),
                                             .btfIn1_re(btfIn1_re),  // sfix28_En14
                                             .btfIn1_im(btfIn1_im),  // sfix28_En14
                                             .btfIn2_re(btfIn2_re),  // sfix28_En14
                                             .btfIn2_im(btfIn2_im),  // sfix28_En14
                                             .btfIn_vld(btfIn_vld)
                                             );

  MINRESRX2_BUTTERFLY u_MinResRX2FFT_BUTTERFLY (.clk(clk),
                                                .reset_x(reset_x),
                                                .enb(enb),
                                                .btfIn1_re(btfIn1_re),  // sfix28_En14
                                                .btfIn1_im(btfIn1_im),  // sfix28_En14
                                                .btfIn2_re(btfIn2_re),  // sfix28_En14
                                                .btfIn2_im(btfIn2_im),  // sfix28_En14
                                                .btfIn_vld(btfIn_vld),
                                                .twdl_re(twdl_re),  // sfix28_En26
                                                .twdl_im(twdl_im),  // sfix28_En26
                                                .syncReset(syncReset),
                                                .btfOut1_re(btfOut1_re),  // sfix28_En14
                                                .btfOut1_im(btfOut1_im),  // sfix28_En14
                                                .btfOut2_re(btfOut2_re),  // sfix28_En14
                                                .btfOut2_im(btfOut2_im),  // sfix28_En14
                                                .btfOut_vld(btfOut_vld)
                                                );

  MINRESRX2FFT_MEMSEL u_MinResRX2FFT_MEMSEL (.clk(clk),
                                             .reset_x(reset_x),
                                             .enb(enb),
                                             .btfOut1_re(btfOut1_re),  // sfix28_En14
                                             .btfOut1_im(btfOut1_im),  // sfix28_En14
                                             .btfOut2_re(btfOut2_re),  // sfix28_En14
                                             .btfOut2_im(btfOut2_im),  // sfix28_En14
                                             .btfOut_vld(btfOut_vld),
                                             .stage(stage),  // ufix4
                                             .initIC(initIC),
                                             .syncReset(syncReset),
                                             .stgOut1_re(stgOut1_re),  // sfix28_En14
                                             .stgOut1_im(stgOut1_im),  // sfix28_En14
                                             .stgOut2_re(stgOut2_re),  // sfix28_En14
                                             .stgOut2_im(stgOut2_im),  // sfix28_En14
                                             .stgOut_vld(stgOut_vld)
                                             );

  MINRESRX2FFT_CTRL u_MinResRX2FFT_CTRL (.clk(clk),
                                         .reset_x(reset_x),
                                         .enb(enb),
                                         .din_1_re(dtc_re),  // sfix28_En14
                                         .din_1_im(dtc_im),  // sfix28_En14
                                         .validIn(validIn),
                                         .stgOut1_re(stgOut1_re),  // sfix28_En14
                                         .stgOut1_im(stgOut1_im),  // sfix28_En14
                                         .stgOut2_re(stgOut2_re),  // sfix28_En14
                                         .stgOut2_im(stgOut2_im),  // sfix28_En14
                                         .stgOut_vld(stgOut_vld),
                                         .syncReset(syncReset),
                                         .dMemIn1_re(dMemIn1_re),  // sfix28_En14
                                         .dMemIn1_im(dMemIn1_im),  // sfix28_En14
                                         .dMemIn2_re(dMemIn2_re),  // sfix28_En14
                                         .dMemIn2_im(dMemIn2_im),  // sfix28_En14
                                         .wrEnb1(wrEnb1),
                                         .wrEnb2(wrEnb2),
                                         .wrEnb3(wrEnb3),
                                         .rdEnb1(rdEnb1),
                                         .rdEnb2(rdEnb2),
                                         .rdEnb3(rdEnb3),
                                         .dMemOut_vld(dMemOut_vld),
                                         .vldOut(vldOut),
                                         .stage(stage),  // ufix4
                                         .rdy(rdy),
                                         .initIC(initIC),
                                         .unLoadPhase(unLoadPhase)
                                         );

  MINRESRX2FFT_OUTMux u_MinResRX2FFT_OUTMUX (.clk(clk),
                                             .reset_x(reset_x),
                                             .enb(enb),
                                             .rdEnb1(rdEnb1),
                                             .rdEnb2(rdEnb2),
                                             .rdEnb3(rdEnb3),
                                             .dMemOut1_re(dMemOut1_re),  // sfix28_En14
                                             .dMemOut1_im(dMemOut1_im),  // sfix28_En14
                                             .dMemOut2_re(dMemOut2_re),  // sfix28_En14
                                             .dMemOut2_im(dMemOut2_im),  // sfix28_En14
                                             .vldOut(vldOut),
                                             .syncReset(syncReset),
                                             .dOut_re(dOut_re),  // sfix28_En14
                                             .dOut_im(dOut_im),  // sfix28_En14
                                             .dout_vld(dout_vld)
                                             );

  assign dataOut_re = dOut_re;

  assign dataOut_im = dOut_im;

  assign validOut = dout_vld;

  assign ready = rdy;

endmodule  // FFT

