open_system('DUALportRAMinterface_v3');
open_system('gm_DUALportRAMinterface_v3');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUALportRAMinterface_v3/PL/integration_block1/D2/Product', 'user4');
hilite_system('DUALportRAMinterface_v3/PL/integration_block1/D2/Product', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUALportRAMinterface_v3/PL/integration_block1/D2/reset_sw4', 'user4');
hilite_system('DUALportRAMinterface_v3/PL/integration_block1/D2/reset_sw4', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUALportRAMinterface_v3/PL/integration_block1/D2/Product1', 'user4');
hilite_system('DUALportRAMinterface_v3/PL/integration_block1/D2/Product1', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUALportRAMinterface_v3/PL/integration_block1/D2/reset_sw5', 'user4');
hilite_system('DUALportRAMinterface_v3/PL/integration_block1/D2/reset_sw5', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUALportRAMinterface_v3/PL/integration_block1/D2/Product2', 'user4');
hilite_system('DUALportRAMinterface_v3/PL/integration_block1/D2/Product2', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUALportRAMinterface_v3/PL/integration_block1/D2/reset_sw6', 'user4');
hilite_system('DUALportRAMinterface_v3/PL/integration_block1/D2/reset_sw6', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUALportRAMinterface_v3/PL/integration_block1/D2/denom_acc11', 'user4');
hilite_system('DUALportRAMinterface_v3/PL/integration_block1/D2/denom_acc11', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUALportRAMinterface_v3/PL/integration_block1/D2/denom_acc2', 'user4');
hilite_system('DUALportRAMinterface_v3/PL/integration_block1/D2/denom_acc2', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUALportRAMinterface_v3/PL/integration_block1/D2/denom_acc3', 'user4');
hilite_system('DUALportRAMinterface_v3/PL/integration_block1/D2/denom_acc3', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUALportRAMinterface_v3/PL/integration_block1/D2/s_state_out11', 'user4');
hilite_system('DUALportRAMinterface_v3/PL/integration_block1/D2/s_state_out11', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUALportRAMinterface_v3/PL/integration_block1/D2/s_state_out2', 'user4');
hilite_system('DUALportRAMinterface_v3/PL/integration_block1/D2/s_state_out2', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DUALportRAMinterface_v3/PL/integration_block1/D2/s_state_out3', 'user4');
hilite_system('DUALportRAMinterface_v3/PL/integration_block1/D2/s_state_out3', 'user4');
