// -------------------------------------------------------------
// 
// File Name: DUAL_port_RAM_and_GA3\hdlsrc\DUALportRAMinterface_v3\MINRESRX2FFT_OUTMux.v
// Created: 2024-05-04 07:38:48
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MINRESRX2FFT_OUTMux
// Source Path: DUALportRAMinterface_v3/PL/integration_block1/FFT/MINRESRX2FFT_OUTMux
// Hierarchy Level: 3
// Model version: 1.38
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MINRESRX2FFT_OUTMux
          (clk,
           reset_x,
           enb,
           rdEnb1,
           rdEnb2,
           rdEnb3,
           dMemOut1_re,
           dMemOut1_im,
           dMemOut2_re,
           dMemOut2_im,
           vldOut,
           syncReset,
           dOut_re,
           dOut_im,
           dout_vld);


  input   clk;
  input   reset_x;
  input   enb;
  input   rdEnb1;
  input   rdEnb2;
  input   rdEnb3;
  input   signed [27:0] dMemOut1_re;  // sfix28_En14
  input   signed [27:0] dMemOut1_im;  // sfix28_En14
  input   signed [27:0] dMemOut2_re;  // sfix28_En14
  input   signed [27:0] dMemOut2_im;  // sfix28_En14
  input   vldOut;
  input   syncReset;
  output  signed [27:0] dOut_re;  // sfix28_En14
  output  signed [27:0] dOut_im;  // sfix28_En14
  output  dout_vld;


  reg signed [27:0] minResRX2FFTOutMux_doutReg_re;  // sfix28
  reg signed [27:0] minResRX2FFTOutMux_doutReg_im;  // sfix28
  reg  minResRX2FFTOutMux_doutReg_vld;
  reg  minResRX2FFTOutMux_rdEnb1Dly;
  reg  minResRX2FFTOutMux_rdEnb2Dly;
  reg  minResRX2FFTOutMux_rdEnb3Dly;
  reg signed [27:0] minResRX2FFTOutMux_doutReg_re_next;  // sfix28_En14
  reg signed [27:0] minResRX2FFTOutMux_doutReg_im_next;  // sfix28_En14
  reg  minResRX2FFTOutMux_doutReg_vld_next;
  reg  minResRX2FFTOutMux_rdEnb1Dly_next;
  reg  minResRX2FFTOutMux_rdEnb2Dly_next;
  reg  minResRX2FFTOutMux_rdEnb3Dly_next;
  reg signed [27:0] dOut_re_1;  // sfix28_En14
  reg signed [27:0] dOut_im_1;  // sfix28_En14
  reg  dout_vld_1;


  // minResRX2FFTOutMux
  always @(posedge clk)
    begin : minResRX2FFTOutMux_process
      if (reset_x == 1'b0) begin
        minResRX2FFTOutMux_doutReg_re <= 28'sb0000000000000000000000000000;
        minResRX2FFTOutMux_doutReg_im <= 28'sb0000000000000000000000000000;
        minResRX2FFTOutMux_doutReg_vld <= 1'b0;
        minResRX2FFTOutMux_rdEnb1Dly <= 1'b0;
        minResRX2FFTOutMux_rdEnb2Dly <= 1'b0;
        minResRX2FFTOutMux_rdEnb3Dly <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            minResRX2FFTOutMux_doutReg_re <= 28'sb0000000000000000000000000000;
            minResRX2FFTOutMux_doutReg_im <= 28'sb0000000000000000000000000000;
            minResRX2FFTOutMux_doutReg_vld <= 1'b0;
            minResRX2FFTOutMux_rdEnb1Dly <= 1'b0;
            minResRX2FFTOutMux_rdEnb2Dly <= 1'b0;
            minResRX2FFTOutMux_rdEnb3Dly <= 1'b0;
          end
          else begin
            minResRX2FFTOutMux_doutReg_re <= minResRX2FFTOutMux_doutReg_re_next;
            minResRX2FFTOutMux_doutReg_im <= minResRX2FFTOutMux_doutReg_im_next;
            minResRX2FFTOutMux_doutReg_vld <= minResRX2FFTOutMux_doutReg_vld_next;
            minResRX2FFTOutMux_rdEnb1Dly <= minResRX2FFTOutMux_rdEnb1Dly_next;
            minResRX2FFTOutMux_rdEnb2Dly <= minResRX2FFTOutMux_rdEnb2Dly_next;
            minResRX2FFTOutMux_rdEnb3Dly <= minResRX2FFTOutMux_rdEnb3Dly_next;
          end
        end
      end
    end

  always @(dMemOut1_im, dMemOut1_re, dMemOut2_im, dMemOut2_re,
       minResRX2FFTOutMux_doutReg_im, minResRX2FFTOutMux_doutReg_re,
       minResRX2FFTOutMux_doutReg_vld, minResRX2FFTOutMux_rdEnb1Dly,
       minResRX2FFTOutMux_rdEnb2Dly, minResRX2FFTOutMux_rdEnb3Dly, rdEnb1,
       rdEnb2, rdEnb3, vldOut) begin
    minResRX2FFTOutMux_doutReg_re_next = minResRX2FFTOutMux_doutReg_re;
    minResRX2FFTOutMux_doutReg_im_next = minResRX2FFTOutMux_doutReg_im;
    if (vldOut) begin
      minResRX2FFTOutMux_doutReg_vld_next = 1'b1;
      if (minResRX2FFTOutMux_rdEnb2Dly || minResRX2FFTOutMux_rdEnb3Dly) begin
        minResRX2FFTOutMux_doutReg_re_next = dMemOut2_re;
        minResRX2FFTOutMux_doutReg_im_next = dMemOut2_im;
      end
      else if (minResRX2FFTOutMux_rdEnb1Dly) begin
        minResRX2FFTOutMux_doutReg_re_next = dMemOut1_re;
        minResRX2FFTOutMux_doutReg_im_next = dMemOut1_im;
      end
      else begin
        minResRX2FFTOutMux_doutReg_vld_next = 1'b0;
      end
    end
    else begin
      minResRX2FFTOutMux_doutReg_vld_next = 1'b0;
    end
    minResRX2FFTOutMux_rdEnb1Dly_next = rdEnb1;
    minResRX2FFTOutMux_rdEnb2Dly_next = rdEnb2;
    minResRX2FFTOutMux_rdEnb3Dly_next = rdEnb3;
    dOut_re_1 = minResRX2FFTOutMux_doutReg_re;
    dOut_im_1 = minResRX2FFTOutMux_doutReg_im;
    dout_vld_1 = minResRX2FFTOutMux_doutReg_vld;
  end



  assign dOut_re = dOut_re_1;

  assign dOut_im = dOut_im_1;

  assign dout_vld = dout_vld_1;

endmodule  // MINRESRX2FFT_OUTMux

