// -------------------------------------------------------------
// 
// File Name: DUAL_port_RAM_and_GA3\hdlsrc\DUALportRAMinterface_v3\output_cast1.v
// Created: 2024-05-04 07:38:49
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: output_cast1
// Source Path: DUALportRAMinterface_v3/PL/integration_block1/D2/output_cast1
// Hierarchy Level: 3
// Model version: 1.38
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module output_cast1
          (in,
           out);


  input   signed [13:0] in;  // sfix14_En12
  output  signed [13:0] out;  // sfix14_En12




  assign out = in;

endmodule  // output_cast1

