// -------------------------------------------------------------
// 
// File Name: DUAL_port_RAM_and_GA3\hdlsrc\DUALportRAMinterface_v3\output_selector_block.v
// Created: 2024-05-04 07:38:49
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: output_selector_block
// Source Path: DUALportRAMinterface_v3/PL/integration_block1/GA_main/coefficent_array1/output_selector
// Hierarchy Level: 4
// Model version: 1.38
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module output_selector_block
          (chose_port,
           In2_0,
           In2_1,
           In2_2,
           In2_3,
           In2_4,
           In2_5,
           In2_6,
           In3_0,
           In3_1,
           In3_2,
           In3_3,
           In3_4,
           In3_5,
           In3_6,
           In4_0,
           In4_1,
           In4_2,
           In4_3,
           In4_4,
           In4_5,
           In4_6,
           In5_0,
           In5_1,
           In5_2,
           In5_3,
           In5_4,
           In5_5,
           In5_6,
           Out1_0,
           Out1_1,
           Out1_2,
           Out1_3,
           Out1_4,
           Out1_5,
           Out1_6);


  input   [3:0] chose_port;  // ufix4
  input   signed [32:0] In2_0;  // sfix33_En15
  input   signed [32:0] In2_1;  // sfix33_En15
  input   signed [32:0] In2_2;  // sfix33_En15
  input   signed [32:0] In2_3;  // sfix33_En15
  input   signed [32:0] In2_4;  // sfix33_En15
  input   signed [32:0] In2_5;  // sfix33_En15
  input   signed [32:0] In2_6;  // sfix33_En15
  input   signed [32:0] In3_0;  // sfix33_En15
  input   signed [32:0] In3_1;  // sfix33_En15
  input   signed [32:0] In3_2;  // sfix33_En15
  input   signed [32:0] In3_3;  // sfix33_En15
  input   signed [32:0] In3_4;  // sfix33_En15
  input   signed [32:0] In3_5;  // sfix33_En15
  input   signed [32:0] In3_6;  // sfix33_En15
  input   signed [32:0] In4_0;  // sfix33_En15
  input   signed [32:0] In4_1;  // sfix33_En15
  input   signed [32:0] In4_2;  // sfix33_En15
  input   signed [32:0] In4_3;  // sfix33_En15
  input   signed [32:0] In4_4;  // sfix33_En15
  input   signed [32:0] In4_5;  // sfix33_En15
  input   signed [32:0] In4_6;  // sfix33_En15
  input   signed [32:0] In5_0;  // sfix33_En15
  input   signed [32:0] In5_1;  // sfix33_En15
  input   signed [32:0] In5_2;  // sfix33_En15
  input   signed [32:0] In5_3;  // sfix33_En15
  input   signed [32:0] In5_4;  // sfix33_En15
  input   signed [32:0] In5_5;  // sfix33_En15
  input   signed [32:0] In5_6;  // sfix33_En15
  output  signed [32:0] Out1_0;  // sfix33_En15
  output  signed [32:0] Out1_1;  // sfix33_En15
  output  signed [32:0] Out1_2;  // sfix33_En15
  output  signed [32:0] Out1_3;  // sfix33_En15
  output  signed [32:0] Out1_4;  // sfix33_En15
  output  signed [32:0] Out1_5;  // sfix33_En15
  output  signed [32:0] Out1_6;  // sfix33_En15


  wire ensure_correct_output_out1;  // ufix1
  wire switch_compare_1;
  wire [3:0] Switch1_out1;  // ufix4
  wire signed [32:0] In2 [0:6];  // sfix33_En15 [7]
  wire signed [32:0] In3 [0:6];  // sfix33_En15 [7]
  wire signed [32:0] In4 [0:6];  // sfix33_En15 [7]
  wire switch_compare_1_1;
  wire [6:0] ensure_correct_output_out1_scalarexpand;  // ufix1 [7]
  wire signed [32:0] ensure_correct_output_out1_scalarexpand_dtc [0:6];  // sfix33_En15 [7]
  wire signed [32:0] In5 [0:6];  // sfix33_En15 [7]
  wire signed [32:0] Multiport_Switch_out1 [0:6];  // sfix33_En15 [7]
  wire signed [32:0] Switch_out1 [0:6];  // sfix33_En15 [7]


  assign ensure_correct_output_out1 = 1'b0;



  assign switch_compare_1 = chose_port > 4'b0000;



  assign Switch1_out1 = (switch_compare_1 == 1'b0 ? 4'b0001 :
              chose_port);



  assign In2[0] = In2_0;
  assign In2[1] = In2_1;
  assign In2[2] = In2_2;
  assign In2[3] = In2_3;
  assign In2[4] = In2_4;
  assign In2[5] = In2_5;
  assign In2[6] = In2_6;

  assign In3[0] = In3_0;
  assign In3[1] = In3_1;
  assign In3[2] = In3_2;
  assign In3[3] = In3_3;
  assign In3[4] = In3_4;
  assign In3[5] = In3_5;
  assign In3[6] = In3_6;

  assign In4[0] = In4_0;
  assign In4[1] = In4_1;
  assign In4[2] = In4_2;
  assign In4[3] = In4_3;
  assign In4[4] = In4_4;
  assign In4[5] = In4_5;
  assign In4[6] = In4_6;

  assign switch_compare_1_1 = chose_port > 4'b0000;



  assign ensure_correct_output_out1_scalarexpand[0] = ensure_correct_output_out1;
  assign ensure_correct_output_out1_scalarexpand[1] = ensure_correct_output_out1;
  assign ensure_correct_output_out1_scalarexpand[2] = ensure_correct_output_out1;
  assign ensure_correct_output_out1_scalarexpand[3] = ensure_correct_output_out1;
  assign ensure_correct_output_out1_scalarexpand[4] = ensure_correct_output_out1;
  assign ensure_correct_output_out1_scalarexpand[5] = ensure_correct_output_out1;
  assign ensure_correct_output_out1_scalarexpand[6] = ensure_correct_output_out1;

  assign ensure_correct_output_out1_scalarexpand_dtc[0] = {17'b0, {ensure_correct_output_out1_scalarexpand[0], 15'b000000000000000}};
  assign ensure_correct_output_out1_scalarexpand_dtc[1] = {17'b0, {ensure_correct_output_out1_scalarexpand[1], 15'b000000000000000}};
  assign ensure_correct_output_out1_scalarexpand_dtc[2] = {17'b0, {ensure_correct_output_out1_scalarexpand[2], 15'b000000000000000}};
  assign ensure_correct_output_out1_scalarexpand_dtc[3] = {17'b0, {ensure_correct_output_out1_scalarexpand[3], 15'b000000000000000}};
  assign ensure_correct_output_out1_scalarexpand_dtc[4] = {17'b0, {ensure_correct_output_out1_scalarexpand[4], 15'b000000000000000}};
  assign ensure_correct_output_out1_scalarexpand_dtc[5] = {17'b0, {ensure_correct_output_out1_scalarexpand[5], 15'b000000000000000}};
  assign ensure_correct_output_out1_scalarexpand_dtc[6] = {17'b0, {ensure_correct_output_out1_scalarexpand[6], 15'b000000000000000}};



  assign In5[0] = In5_0;
  assign In5[1] = In5_1;
  assign In5[2] = In5_2;
  assign In5[3] = In5_3;
  assign In5[4] = In5_4;
  assign In5[5] = In5_5;
  assign In5[6] = In5_6;

  assign Multiport_Switch_out1[0] = (Switch1_out1 == 4'b0001 ? In2[0] :
              (Switch1_out1 == 4'b0010 ? In3[0] :
              (Switch1_out1 == 4'b0011 ? In4[0] :
              In5[0])));
  assign Multiport_Switch_out1[1] = (Switch1_out1 == 4'b0001 ? In2[1] :
              (Switch1_out1 == 4'b0010 ? In3[1] :
              (Switch1_out1 == 4'b0011 ? In4[1] :
              In5[1])));
  assign Multiport_Switch_out1[2] = (Switch1_out1 == 4'b0001 ? In2[2] :
              (Switch1_out1 == 4'b0010 ? In3[2] :
              (Switch1_out1 == 4'b0011 ? In4[2] :
              In5[2])));
  assign Multiport_Switch_out1[3] = (Switch1_out1 == 4'b0001 ? In2[3] :
              (Switch1_out1 == 4'b0010 ? In3[3] :
              (Switch1_out1 == 4'b0011 ? In4[3] :
              In5[3])));
  assign Multiport_Switch_out1[4] = (Switch1_out1 == 4'b0001 ? In2[4] :
              (Switch1_out1 == 4'b0010 ? In3[4] :
              (Switch1_out1 == 4'b0011 ? In4[4] :
              In5[4])));
  assign Multiport_Switch_out1[5] = (Switch1_out1 == 4'b0001 ? In2[5] :
              (Switch1_out1 == 4'b0010 ? In3[5] :
              (Switch1_out1 == 4'b0011 ? In4[5] :
              In5[5])));
  assign Multiport_Switch_out1[6] = (Switch1_out1 == 4'b0001 ? In2[6] :
              (Switch1_out1 == 4'b0010 ? In3[6] :
              (Switch1_out1 == 4'b0011 ? In4[6] :
              In5[6])));



  assign Switch_out1[0] = (switch_compare_1_1 == 1'b0 ? ensure_correct_output_out1_scalarexpand_dtc[0] :
              Multiport_Switch_out1[0]);
  assign Switch_out1[1] = (switch_compare_1_1 == 1'b0 ? ensure_correct_output_out1_scalarexpand_dtc[1] :
              Multiport_Switch_out1[1]);
  assign Switch_out1[2] = (switch_compare_1_1 == 1'b0 ? ensure_correct_output_out1_scalarexpand_dtc[2] :
              Multiport_Switch_out1[2]);
  assign Switch_out1[3] = (switch_compare_1_1 == 1'b0 ? ensure_correct_output_out1_scalarexpand_dtc[3] :
              Multiport_Switch_out1[3]);
  assign Switch_out1[4] = (switch_compare_1_1 == 1'b0 ? ensure_correct_output_out1_scalarexpand_dtc[4] :
              Multiport_Switch_out1[4]);
  assign Switch_out1[5] = (switch_compare_1_1 == 1'b0 ? ensure_correct_output_out1_scalarexpand_dtc[5] :
              Multiport_Switch_out1[5]);
  assign Switch_out1[6] = (switch_compare_1_1 == 1'b0 ? ensure_correct_output_out1_scalarexpand_dtc[6] :
              Multiport_Switch_out1[6]);



  assign Out1_0 = Switch_out1[0];

  assign Out1_1 = Switch_out1[1];

  assign Out1_2 = Switch_out1[2];

  assign Out1_3 = Switch_out1[3];

  assign Out1_4 = Switch_out1[4];

  assign Out1_5 = Switch_out1[5];

  assign Out1_6 = Switch_out1[6];

endmodule  // output_selector_block

