// -------------------------------------------------------------
// 
// File Name: DUAL_port_RAM_and_GA3\hdlsrc\DUALportRAMinterface_v3\random_sample.v
// Created: 2024-05-04 07:38:48
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: random_sample
// Source Path: DUALportRAMinterface_v3/PL/integration_block1/Subsystem/random_sample
// Hierarchy Level: 3
// Model version: 1.38
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module random_sample
          (u1,
           u2,
           Out1);


  input   u1;
  input   u2;
  output  [3:0] Out1;  // ufix4


  wire [1:0] concat1_out1;  // ufix2
  wire [3:0] Data_Type_Conversion15_out1;  // ufix4
  wire [3:0] Add10_out1;  // ufix4


  assign concat1_out1 = {u1, u2};



  assign Data_Type_Conversion15_out1 = {2'b0, concat1_out1};



  assign Add10_out1 = Data_Type_Conversion15_out1 + 4'b0001;



  assign Out1 = Add10_out1;

endmodule  // random_sample

